### ISSUE TITLE
Images get author colors as background on the sides even with author colors disabled

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/text#1852] opened 2021-09-07 13:37 UTC
**Describe the bug**
Even with author colors disabled, inserted images get the author color shown in the background. Seems you have to remove the picture first and then undo in some cases:
![images get background color even without author colors](https://user-images.githubusercontent.com/925062/132354121-53bca10d-6a6f-45c1-bad8-5c9cf590a39f.png)

**Expected behavior**
When author colors are disabled, the images don’t show the author color as background around them.

**Comment by juliushaertl** [comment] 2021-09-07 13:52
Duplicate of #1779

**Closed by juliushaertl** 2021-09-07 13:52 UTC
Labels: bug, 0. Needs triage
