### ISSUE TITLE
Allow Customizing Rich Workspace Filename

### ISSUE THREAD

**Issue by gary-kim** [nextcloud/text#727] opened 2020-03-24 04:18 UTC
**Is your feature request related to a problem? Please describe.**
Personally, my readme files are already stored with the filename `README.md`. I'd like to keep it this way.

**Describe the solution you'd like**
A way to configure the filename of files created by rich workspace.

**Describe alternatives you've considered**
I personally use my own customized version of Nextcloud so I've added it as a patch in the build process for my version but it'd be nice if the ability to customize it was included.

The main issue is where would a setting like this go in the interface? This feels too minute a setting to even put in the new Files settings area so I'm not sure where this would go. My immediate thinking would be systemwide setting but this seems more like the kind of thing individual users may want to customize. Maybe this is more the kind of thing that is suitable for someone to just build their own version for if they care about minute details this much.

I can make a PR for whatever we decide to do.

cc @jancborchardt

**Comment by jancborchardt** [comment] 2020-03-24 10:51
So the issue is that we use "Readme.md" and you’d like "README.md", right?
We intentionally use the non-all-caps version here for better readability and as generally non-tech people are not used to this convention of all-capsing files like LICENSE, README etc.

> The main issue is where would a setting like this go in the interface? This feels too minute a setting to even put in the new Files settings area so I'm not sure where this would go. My immediate thinking would be systemwide setting but this seems more like the kind of thing individual users may want to customize. Maybe this is more the kind of thing that is suitable for someone to just build their own version for if they care about minute details this much.

I’d agree here – it’s too minute to warrant a setting, I wouldn’t even put it in the config.php cause we still have to test and maintain. :\ This seems really only something for patching on people’s own instances if they so desire.

What we could do, if we do anything at all, is that if you rename a Readme.md to README.md, to switch the default to that. The question is if we do the same for "readme.md" or any other name change as well.

-----

One thing actually: Do we translate the name, and should we? Cause as non-english user, "Readme" is still quite strange.

@juliushaertl what do you think?

**Comment by sam-19** [comment] 2020-04-02 17:45
I would love this feature too. In fact, I wouldn't care what the name of the file is as long as I could configure it to start with a dot, to hide it. Right now, I have folders of photos on my server, where I can finally add a description (like an event, date, people involved, camera used or whatever) on top of the folder and browse the photos neatly in a grid view... until there is a big ol' Readme.md in the middle of those photos, sticking out like a sore thumb. Or maybe there is an occ command to hide the file already, and I just haven't figured it out?

**Comment by juliushaertl** [comment] 2020-04-02 18:27
> One thing actually: Do we translate the name, and should we? Cause as non-english user, "Readme" is still quite strange.

I was just checking and while we indeed translate when checking, we do not do that on creation. I remember we discussed this when working on this feature that the filenames should be translated. I'll prepare a fix for that.

> So the issue is that we use "Readme.md" and you’d like "README.md", right? And just to clarify, the README.md should also work as in being shown up top, regardless of capitalization, correct?

Yes, translated.md, README.md, Readme.md and readme.md will be picked up in that order if present.

> I’d agree here – it’s too minute to warrant a setting, I wouldn’t even put it in the config.php cause we still have to test and maintain. :\ This seems really only something for patching on people’s own instances if they so desire.

:+1:

**Comment by gary-kim** [comment] 2020-04-04 06:55
> Yes, translated.md, README.md, Readme.md and readme.md will be picked up in that order if present.

Sounds like that could be weird if someone changes their language. Would older READMEs not be picked up?

**Comment by jancborchardt** [comment] 2020-04-20 21:00
Closing as per @juliushaertl’s reply then.

> Sounds like that could be weird if someone changes their language. Would older READMEs not be picked up?

@juliushaertl can you clarify that? :)

**Closed by jancborchardt** 2020-04-20 21:00 UTC
Labels: enhancement

**Comment by juliushaertl** [comment] 2020-04-21 08:02
> Sounds like that could be weird if someone changes their language. Would older READMEs not be picked up?

Yes, that is true, but I don't see a proper way around when keeping translated readme names.
