### ISSUE TITLE
Nextcloud for iOS don't detect the Text app

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/text#1662] opened 2021-06-16 10:38 UTC
Despite having installed the Text app the endpoint:

ocs/v2.php/apps/files/api/v1/directEditing?format=json

return:

▿ 1 element
  ▿ 0 : 2 elements
    - key : ocs
    ▿ value : 2 elements
      ▿ 0 : 2 elements
        - key : meta
        ▿ value : 3 elements
          ▿ 0 : 2 elements
            - key : status
            - value : ok
          ▿ 1 : 2 elements
            - key : statuscode
            - value : 200
          ▿ 2 : 2 elements
            - key : message
            - value : OK
      ▿ 1 : 2 elements
        - key : data
        ▿ value : 2 elements
          ▿ 0 : 2 elements
            - key : editors
            - value : 0 elements
          ▿ 1 : 2 elements
            - key : creators
            - value : 0 elements { ... }

I have only the server Version 20.0.8 (sorry)

**Comment by juliushaertl** [comment] 2021-06-17 10:19
@foss- @WernerBleisteiner Since you reported the original issue on the iOS app, could you please fill out the issue template from here https://github.com/nextcloud/text/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md and also check the server logs if there are any issues reported related to the directEditing request?

**Comment by WernerBleisteiner** [comment] 2021-06-17 11:55
Hi! Thanks.
I got my issue eventually solved by moving to NC 20 some tome ago.
So at the moment no mor problems.

**Comment by abnerhale** [comment] 2021-06-25 20:39
Same Problem here:

I have two nextcloud instances:
Production:
20.0.10
Text App 3.1.0
In IOS APP  Text "Not available"  - No Text editing or creation is possible
(Running Text App iin Webbrowser works fine)

Test:

21.0.1
Text App 3.2.0
IOS APP Text "Available" - Works fine

Both were checked with IOS Nextcloud Liquid 4.0.3.0.
Both instances run on same host with same MySQL and PHP Version

**Comment by foss-** [comment] 2021-07-28 11:55
NC instance updated to 21.0.3 (from 20.0.8 in initial report) so revisiting issue which is persisting.

**Client details:**
 - OS: iOS 14.7.1
 - Browser: N/A
 - Version: 21.0.3
 - Device: iPhone xR

<details>
<summary>Server details</summary>


**Text app version:** (see Nextcloud apps page)

**Operating system:**

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** 21.0.3
iOS NextCloud 4.0.5 > Settings > Extended > Capabilities: (1 month)
https://bin.disroot.org/?f689eb351cef8383#D9S78QQk3XVu7ad5R7QLJUae3h9H6JNm8UMWHMMptPRp

</details>



<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

@juliushaertl thanks for the feedback and excuse the late feedback. I wanted to wait for the NC update to see if that resolves teh problem - sadly it does not. I requested the server log info and will update the post as soon as I have news.

**Comment by max-nextcloud** [comment] 2022-11-14 08:09
I'm wondering if this still is an issue with the more current nextcloud versions - that is 23, 24 or 25.

@marinofaggiana are you aware of users experiencing the same in recent versions of nextcloud?

I'm tempted to close this as NC 20 and 21 are not supported anymore. But first I want to check if it still is an issue.

**Comment by max-nextcloud** [comment] 2022-11-14 08:34
Just checked with @marinofaggiana and he has not seen this in a long time. So I'll close the issue. Feel free to reopen / open a new one in case it comes back.

**Closed by max-nextcloud** 2022-11-14 08:34 UTC
Labels: bug, needs triage: max

**Comment by foss-** [comment] 2023-04-24 09:57
Can we please re-open this. The issue never got resolved. The instance in question has been updated to 25.0.5 and the issue is persisting.

We have two related issues:

https://github.com/nextcloud/text/issues/3762 which is a duplicate of this issue here
https://github.com/nextcloud/text/issues/3892 which reports the same problem on Android OS

Probably the title should be adjusted and the issues gathered in a single issue.

This issue imo was never limited to either iOS or Android but always affected both OSs. I have a suspicion that once this is solved, things will work on both platforms, since after all the issue seems to be server side not client side. It is just the clients that expose the symptom, since the server seems to think Text app is not installed which is probably a result of caching gone wrong or information not being correctly updated when altered.

**Comment by foss-** [comment] 2023-06-02 15:38
Polite pinging @marinofaggiana @max-nextcloud @juliushaertl
