### ISSUE TITLE
Cypress memory leaks crash browser after some runs

### ISSUE THREAD

**Issue by max-nextcloud** [nextcloud/text#3498] opened 2022-11-29 11:09 UTC
**Describe the bug**
Each test run leaves large amounts of data on the heap. With the default settings and the shortcuts spec it's approx. 600 MB.
These will stay on the heap and accumulate. So after the second test run it's 1.2 GB.

**To Reproduce**
1. Open cypress test in the browser
2. Open developer tools with memory tab
3. Run the test multiple times
4. See heap size grow until it comes to a grinding halt at the fourth test run

**Expected behavior**
There should be no leftovers from previous tests on the heap.

**Screenshots**

**Client details:**
 - Cypress: 11.2.0
 - Browser: chrome, electron, firefox
 - Version: current master branch

### Mitigation:

Setting `numTestsKeptInMemory` in the config will reduce the size of the data on the heap per test run. The default is 50. If set to 10 shortcuts spec will only take up 400 MB of heap for each run. If set to 1 it's below 40 MB. But snapshots of previous tests are also not available anymore. These snapshots are also what makes up most of the data on the heap.

**Comment by mejo-** [comment] 2023-06-20 10:21
Well, this is still a thing, I was able to reproduce. But not sure what whould be a way forward here, @max-nextcloud. I don't think we should lower `numTestsKeptInMemory` - because we want to be able to access the snapshots of tests in the spec that ran last.

This should not become an issue in the CI because we don't rerun whole specs there. And when running locally, the main downside is that you have to restart Cypress from time to time, no? To be honest I don't think it's worth further investigation and work on your side.

I'll close the issue for now, but feel free to reopen if you're keen to tackle it @max-nextcloud.

**Closed by mejo-** 2023-06-20 10:21 UTC
Labels: bug, tests, dependencies, upstream, needs triage: jonas
