### ISSUE TITLE
disconnects at image upload

### ISSUE THREAD

**Issue by whoeveritis** [nextcloud/text#4153] opened 2023-05-07 08:50 UTC
opening a .md file and adding some images works usually with first image only, any following image will only upload after a fresh login to nextcloud. Also editing text results in many disconnects and 'toastify is awesome' splash screens. Here is my .md example file https://wolkenmeer.com/index.php/s/DSt5ZLX2QJGtC2i .

**Comment by mejo-** [comment] 2023-05-07 10:22
Dear @whoeveritis, thanks for your report. Unfortunately it lacks some important information:

* How to you upload the images? With drag and drop? Via the "Upload from computer" option from the toolbar menu?
* Which Nextcloud version is your instance running?
* Which browser and version do you use?
* Do you see related errors in the `nextcloud.log` file? Best is to watch this file while reproducing the bug. Please paste any logs lines that get added while reproducing the bug.
* When opening the browser console (<Ctrl>-<Shift>-<I> in most browsers and there the "Console" tab), do you see anything being logged there while reproducing the error?

**Comment by whoeveritis** [comment] 2023-06-02 11:01
sorry for, I hoped it was complete ;(
1) usually I upload images or other data by saving them into my local NC sync folder. Nextcloud use via browser I rather avoid.
2) I am running NextCloud 25.0.6 (hosted by owncube.com)
3) my main Browser is Firefox 114.0 on MacOSX (or newer)
4) I am not very capable on interpreting those logs I am afraid. My two other macs ron Nextcloud sync 3.8.2 which behaves as it should.
5) this is not an error related to a browser. It is an error with Nextcloud sync (above 3.8.2) client for Mac OSX 11.7.8 Big Sur.
6) currently I seem to be stuck with NCsync for OSX Version 3.8.2 and I will not update these.

**Comment by mejo-** [comment] 2023-06-06 13:20
Dear @whoeveritis, thanks for the additional information. I'm a bit confused: do you have problems with uploading images to markdown files using the Nextcloud Text editor? Or do you have problems with synchronizing files from your Mac to Nextcloud using the Desktop Sync Client? Your original report sounded like the former, now it rather sounds like the latter :wink:

**Comment by whoeveritis** [comment] 2023-06-08 06:09
hollo, sorry I was confused myself... Actually I have both problems and I mixed them - a) Working with Images in NextCloud text has the problem of frequent disconnetcint at image upload and b) my NextClud desktop client for OSX does not work as expected. Most times it is not able to deliver any links.

**Comment by mejo-** [comment] 2023-07-12 11:05
Let's focus on the issues you face when uploading attachments/images to Nextcloud Text documents in this issue.

How to you upload the images? With drag and drop? Via the "Upload from computer" option from the toolbar menu?

To get a better understanding of your issue, we need further information.

Please open the web console of your browser (<kbd>Ctrl</kbd>-<kbd>Shift</kbd>-<kbd>I</kbd> on Firefox/Chrome), reproduce the issue with uploading attachments/images to a Text document and send us any errors or warnings being logged there.

Furthermore, please send us relevant logs from the `nextcloud.log` file on your server that appear while experiencing the issue.

**Comment by mejo-** [comment] 2023-07-25 06:17
Let's close this issue due to lack of information for now. @whoeveritis feel free to reopen if you still experience the issue, but please provide the further information I requested in that case :relaxed:

**Closed by mejo-** 2023-07-25 06:17 UTC
Labels: bug, needs info

**Comment by websuitesolution** [comment] 2023-10-12 22:26
<img width="770" alt="Screenshot 2023-10-13 at 6 24 18 AM" src="https://github.com/nextcloud/text/assets/138292847/5071a612-cb89-464f-8065-099bd5257613">
