### ISSUE TITLE
Placeholder text on empty newlines to advertise pickers (emoji, mention, smart picker)

### ISSUE THREAD

**Issue by mejo-** [nextcloud/text#6408] opened 2024-09-16 09:08 UTC
We should add a placeholder on empty paragraphs when cursor is inside. It should advertise the pickers (emoji, mention, smart picker).

This is how it looks like on notion:

| Screenshot |
| --- |
| ![2024-09-16T11:07:00,506168105+02:00](https://github.com/user-attachments/assets/ef37c258-638a-43b6-b317-1ada590c3c1e) |

**Comment by juliushaertl** [comment] 2024-09-16 14:17
Duplicate of #4619

**Closed by juliushaertl** 2024-09-16 14:17 UTC
Labels: enhancement, feature: formatting, 1. to develop
