### ISSUE TITLE
Table of content is not scrollable if it is too long

### ISSUE THREAD

**Issue by lilian-pouliquen** [nextcloud/text#3823] opened 2023-02-23 21:08 UTC
**Describe the bug**
When reading a document shared by link with many titles, the table of content displayed is not scrollable and I cannot access the cropped items.

**To Reproduce**
1. Access the document with many titles through a share link (in my case it is a read only document)
2. Click on "Show outline"
3. Notice the missing items in the TOC

**Expected behavior**
I can navigate through my document with the table of content with all the items.

**Client details:**
 - OS: Fedora 37
 - Browser: Librewolf (Firefox)
 - Version: 109.0.1
 - Device: Laptop

<details>
<summary>Server details</summary>

**Text app version:** 3.6.0

**Operating system:** Alpine Linux 3.16.3

**Web server:** Apache HTTPD 2.4.55

**Database:** PostrgreSQL 15.1

**PHP version:** 8.1.14 FPM

**Nextcloud version:** 25.0.3

**NOTE:** I am using Docker to run Nextcloud. I use the image `nextcloud:25.0.3-fpm-alpine`.

</details>

<details>
<summary>Logs</summary>

#### Browser log
```
JS logs when opening the outline:
    $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. (globals.js:60:15)
```

</details>

Thank you for your help.

**Comment by juliushaertl** [comment] 2023-03-07 09:35
@luka-nextcloud could you check that? Should be a quick fix

**Comment by mejo-** [comment] 2023-03-07 16:54
This is a duplicate of #3585

**Closed by mejo-** 2023-03-07 16:54 UTC
Labels: bug
