### ISSUE TITLE
Export Note to PDF

### ISSUE THREAD

**Issue by grizzee** [nextcloud/text#909] opened 2020-06-30 14:38 UTC
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
an option to export the note in a PDF.

**Describe alternatives you've considered**
download the Note, open in a Markdowneditor of choice, export to PDF

**Additional context**
-

**Comment by juliushaertl** [comment] 2020-07-15 11:26
Duplicate of #112

**Closed by juliushaertl** 2020-07-15 11:26 UTC
Labels: enhancement
