### ISSUE TITLE
Tables inside the markdown files

### ISSUE THREAD

**Issue by PifPof73** [nextcloud/text#1034] opened 2020-09-10 14:01 UTC
In the extended Markdown Syntax, tables can easily be coded inside markdown documents. [https://www.markdownguide.org/extended-syntax/](https://www.markdownguide.org/extended-syntax/)

This would be a nice feature, since Tables are very common and present structured data very clearly.

I have tested the example:

`| Syntax      | Description |`
`| ----------- | ----------- |`
`| Header      | Title       |`
`| Paragraph   | Text        |`

For which the github markdown parser generates:

| Syntax      | Description |
| ----------- | ----------- |
| Header      | Title       |
| Paragraph   | Text        |

Regards,
PifPof73

**Comment by juliushaertl** [comment] 2020-09-11 05:56
Duplicate of https://github.com/nextcloud/text/issues/114

**Closed by juliushaertl** 2020-09-11 05:56 UTC
Labels: enhancement
