### ISSUE TITLE
Unable to resolve conflict on mobile client

### ISSUE THREAD

**Issue by btittelbach** [nextcloud/text#1582] opened 2021-05-06 08:29 UTC
**Describe the bug**

When choosing to edit a downloaded file on mobile (Android) client, that has been modified remotely, the Sync Conflict Dialog appears, prompting "The document has been changed outside of the editor. The changes cannot be applied"

Then, touching "Use the saved version" does nothing.

To resolve the conflict, user has to login using a webbrowser.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create file `test.md` and fill with testdata
2. On mobile edit file `test.md`
3. On mobile select "Download" from `file test.md`'s menu
5. Quickly edit file on pc, so a new conflicting version will be synced via nextcloud-desktop client.
6. Edit file on mobile/android.
7. Sync Conflict Dialog will appear
8. Click _Use the saved version_

**Expected behavior**
I except the editor to open and being able to edit the saved version.

**Actual behavior**
- The left side, showing the (old) local version, is emptied
- Then the Sync Conflict Dialog stays as it is.
- The editor does not appear.
- This continues to happen, no matter how often the mobile client tries to edit the document.

**Screenshots**
![text_conflict_Screenshot_20210506-095952](https://user-images.githubusercontent.com/635660/117264047-2454fc00-ae53-11eb-8676-2bafdf3aac37.png)

**Client details:**
 - OS: Android 9
 - Browser: Nextcloud Android app
 - Version: 3.15.1
 - Device: Android Phone

<details>
<summary>Server details</summary>

**Text app version:** 3.2.0

**Operating system:** GNU/Linux, Android

**Web server:** nginx/1.17.10 (Ubuntu)

**Database:** mysql  Ver 8.0.23-0ubuntu0.20.04.1 for Linux on x86_64 ((Ubuntu))

**PHP version:** 7.4

**Nextcloud version:**  21.0.1

</details>

**Comment by marbx** [comment] 2022-10-22 20:27
I have the same problem, with *.md and *.txt files.

What does "needs triage" mean?
How can I help?

**Comment by marcelklehr** [comment] 2022-10-24 14:39
Hey @marbx

needs triage is an internal label we are using to organize bug triage. I'm going to try to reproduce this bug now for example :)

**Comment by marbx** [comment] 2022-10-24 16:25
Hi @marcelklehr , oh good, this issue is bugging me a lot.

I just reproduced it with:
1. Edit file on Android, keep editor open
2. Edit same file on desktop (Debian),

In "normal life" I don't use desktop and Android at the same time, and I am the only user of my NextCloud.
So there must be other conditions, but the buggy dialog @btittelbach pasted is the same at all times.

**Comment by marcelklehr** [comment] 2022-10-25 12:54
Which versions of Nextcloud and the Nextcloud android app are you using?

When using NC 25 and the latest Android app, I get the text editor in the Android app and the desktop client locks the file as readonly, so I can't edit it. Maybe the file lock app is necessary for this to work. cc @juliushaertl

**Comment by marbx** [comment] 2022-10-26 16:45
Android Version is 3.22.1
Server is managed by hosting,de, version 24.0.6
I assume "the file lock app" is on the server?

I opened a *.txt file on a second Android device and the editor presented the unrecoverable conflict dialog.
This was hours after I edited that file on any other device.

Syncing the file does not help.
Syncing the folder does not help.
The only workaround I have is to copy the file on the dektop and delete the original file.
Only renaming the file does not help.

**Comment by marcelklehr** [comment] 2022-11-04 08:04
With Nextcloud 25, Android 3.22.2 and Nextcloud Desktop 3.5.4 I cannot reproduce this:

- When Pressing Edit in Android, the file will get locked on the desktop and I can only open as readonly.
- When Opening the file on the desktop before Editing on Android I get asked whether I want to override changes from elsewhere.
- I never get shown the Conflicts dialog on Android.

When opening a different application to edit the file, I do manage to get conflicts on Android, but the Conflicts dialog doesn't have the bug you describe for me: I can select the local copy and can recover from the conflict.

I'll thus close this as fixed in the latest version(s).

**Closed by marcelklehr** 2022-11-04 08:04 UTC
Labels: bug, needs info, needs triage: marcel

**Comment by edvfreak** [comment] 2023-08-31 22:08
Not resolved. Still exists on Nextcloud 27.0.2 with newest android app 3.25.0. create .txt in Windows. Simply browse and select file to open within android. Text editor opens up automatically. Make changes and go back and forth a few times. Conflicts will come. Changes made in windows an hour prior to opening same file on Android will still throw a conflict dialog asking if local or server copy of file shall be kept. Selecting server file does not work stablely. Sometimes the content from server file is applied to the local file being edited, sometimes the server side changes get lost at this point and the Android Client overwrites the newer version of the file on the server. Data loss occurs as Android conflict Resolution dialog is still buggy. Please fix!

**Comment by marbx** [comment] 2023-09-02 19:19
Just today: conflict appears on Android, neither "Use..." option has an effect.

After a while, conflict disappeared, but I regularly have to copy to a new file on Linux because the conflict is permanent.


I think these are a low level problems and no project priorities.
