### ISSUE TITLE
Tiny text and huge margins

### ISSUE THREAD

**Issue by mobamoba** [nextcloud/text#4620] opened 2023-08-02 11:05 UTC
I'm not sure if this is a bug or not but this is how all of my notes look - NC latest and all apps updated. It's a huge waste of space plus really difficult to read. Is there any way to fix this? It's a rich text thing because if I turn it off, the font is bigger and more space is used. 

In Rich text on (below), the margin starts at the Deck app edge (next to the music note) and there's an entire extra paragraph because the font is so much smaller; in rich text off, it starts at the magnifying glass. You can also see how the font is smaller in the rich text than when it's off.

Rich text on:
<img width="1025" alt="Screenshot 2023-08-02 at 07-07-28 Notes - Nextcloud" src="https://github.com/nextcloud/text/assets/11135869/43b287c6-6a4d-4871-8587-90181dd9122e">

Rich text off:

<img width="1023" alt="Screenshot 2023-08-02 at 07-06-12 What is Lorem Ipsum - Notes - Nextcloud" src="https://github.com/nextcloud/text/assets/11135869/d858a818-507f-4366-beaf-a2797e98edf4">

**Comment by juliushaertl** [comment] 2023-08-06 20:31
This seems to be a duplicate of https://github.com/nextcloud/text/issues/4024 therefore closing it here.

**Closed by juliushaertl** 2023-08-06 20:31 UTC
