### ISSUE TITLE
plain text editor in Nextcloud Text?

### ISSUE THREAD

**Issue by devnull4242** [nextcloud/text#1367] opened 2021-01-20 10:29 UTC
**Is your feature request related to a problem? Please describe.**
Sometimes there is an error in my markdown structure and i must change the plain text file (e.g. ```).
Sometimes i want to copy parts of other markdown files in a new markdown file.

**Describe the solution you'd like**
At the top a button to change to plain text file edit like app https://apps.nextcloud.com/apps/files_texteditor

**Describe alternatives you've considered**
Exit Markdown editor and open Plain text editor (i must install both editors in Nextcloud)

**Additional context**
No additional context.

**Comment by claell** [comment] 2021-03-13 11:18
Duplicate of #123

**Comment by claell** [comment] 2021-03-13 11:19
Looks like a duplicate, please follow up there or comment here again if you don't think that is correct.

**Closed by claell** 2021-03-13 11:19 UTC
Labels: enhancement
