### ISSUE TITLE
Files take around 20 seconds to load

### ISSUE THREAD

**Issue by RuudschMaHinda** [nextcloud/text#2028] opened 2021-12-22 11:16 UTC
**Describe the bug**
Whenever a .txt, .md, .sh file is opened it takes about 20 seconds to load said file.
Might it be, that this is particular to my installation? I do not use self signed certificates, and I have used the search on here, and with different search engines to find any kind of solution.
If just uninstalling the app, and clearing it's DB-Entries would help (would need to know which entries to clean though), that would already be awesome.

**To Reproduce**
Open any simple text file supported by "text".

**Expected behavior**
File opens within one second

**Screenshots**
![image](https://user-images.githubusercontent.com/6041609/147084010-2ac2f3ae-7222-4a99-bb3d-d7698bb8ace3.png)

**Client details:**
This happens in Firefox, as well as in Chromium and Chrome

<details>
<summary>Server details</summary>

**Text app version: ** latest

**Operating system:** Ubuntu 20.04 Server

**Web server:** nginx

**Database:** MariaDB 17

**PHP version:** php-fpm8.0

**Nextcloud version:** 23.0.0.10 (upgraded since owncloud 5 or 6)

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
unfortunately no log entries are produced from opening text files on log level 2

</details>

**Comment by mejo-** [comment] 2022-01-13 11:57
Hey @RuudschMaHinda, thanks for your report.

That's indeed unexpected behaviour and we're not aware of performance issues in the text app that could explain such long waiting periods. Do other apps and functions on your Nextcloud instance cause similar long delays? How is it with file operations in the files app, e.g. when you upload a very small file or copy one from one folder to another?

**Comment by RuudschMaHinda** [comment] 2022-01-13 12:32
All other apps (afaik) function without such an unexpected, or obvious delay.

I created a small test file `echo "1" > test.txt` and uploaded it via drag and drop. It did take about 20 Seconds after the 2 Bytes have been uploaded for the file to appear and the status bar to disappear.
Copying it within the Web-UI worked without any problems or delays and it immediately worked.

In short:
Other apps work as expected
Copying small files within Web-UI works as expected
Uploading a small file takes about 20 seconds to register
![image](https://user-images.githubusercontent.com/6041609/149330705-9a71b71f-3dd1-46bb-bacb-cae4a791addd.png)

**Comment by juliushaertl** [comment] 2022-10-17 17:26
If uploading a file takes that long as well this does not seem to be a text app issue. 

In case the storage itself is fast it might be caused by another app that has a pre/post file write hook or maybe a workflow. You could try to narrow this down by disabling individual apps one after another and see if any of those disabled improves the situation. 

I'll close this here as it is unrelated to the text app, but the best place to ask for help might be our forum at help.nextcloud.com

**Closed by juliushaertl** 2022-10-17 17:26 UTC
Labels: bug, needs info, needs triage: julius
