### ISSUE TITLE
Issue with Link Tooltop in Firefox

### ISSUE THREAD

**Issue by nickian** [nextcloud/text#600] opened 2020-01-21 20:13 UTC
NextCloud version: 17.0.2
Text version: 1.1.1
Firefox: 72.0.1

I can't add links to text in Firefox. This is what it looks like. When I try to click the tooltip it just goes away.

<img width="631" alt="Screen Shot 2020-01-21 at 1 11 10 PM" src="https://user-images.githubusercontent.com/590678/72839538-b251a700-3c4f-11ea-9718-783f1a862180.png">

As a side note, it would also be nice to have a source editing option in the browser, not just wysiwyg.

**Comment by ahstro** [comment] 2020-02-25 01:29
Is this still happening and/or can someone else reproduce it? I tried in both Firefox 73.0.1 and Firefox Developer Edition 74.0b4, but it worked fine, and being on Arch, I can't easily install a previous version.

**Comment by nickian** [comment] 2020-02-25 06:50
Yes, still an issue for me on Windows 10 and MacOS, Firefox 73.0.1. The input comes up, but doesn't look right. It's cut off on the left side and just doesn't behave the same as Chrome.

![34234234](https://user-images.githubusercontent.com/590678/75222001-65865200-5760-11ea-8661-55f103daf2c1.jpg)

**Comment by ahstro** [comment] 2020-02-25 10:38
Hmm, that looks like a different issue to me, specifically the menu bubble not showing up correctly on too narrow editor windows. I'll look into that right away 😊

But in which way is it behaving differently? I'll try to help with that as much as possible, but unfortunately(?) I'm getting the same behavior from all my browsers 😅

**Comment by ahstro** [comment] 2020-02-25 12:15
The alignment issue seems to be an upstream one: https://github.com/scrumpy/tiptap/pull/239
It is allegedly fixed, but since that doesn't seem to be the case here, I asked the creator of the original PR.

Still, if something other than the alignment is off, share! 😊

**Comment by nickian** [comment] 2020-02-25 22:43
On Mac OS, I am not able to get the textbox to appear:

![text](https://user-images.githubusercontent.com/590678/75294206-0a4a7300-57e5-11ea-9a33-fb3d81577b21.gif)

On Windows, it works, but if I'm trying to add a link that happens to be on the left side of the document, the popup ends up going too far left and getting cut off. Maybe some conditional logic that says if the selected text is x pixels away from the left edge, then increase left positioning by however much is needed to not cut off.

**Comment by nickian** [comment] 2020-02-25 22:47
Actually the left positioning issue seems to be universal. This is in Chrome on Mac OS, as an example:

![text2](https://user-images.githubusercontent.com/590678/75294590-13880f80-57e6-11ea-9f53-39e0e413df16.gif)

**Comment by nickian** [comment] 2020-02-25 23:26
Also, I can't help but wonder, why not just have the link icon in the menu with the rest of the items instead of this tooltip approach? Seems inconsistent and arbitrary.

**Comment by ahstro** [comment] 2020-02-26 00:51
This app is using [tiptap](https://github.com/scrumpy/tiptap) for the editor, so I'm assuming the Nextcloud-people didn't make a lot of the design decisions, but yeah, I agree that it seems arbitrary. It's also in tiptap where the left alignment issue is.

I don't have access to a Mac, so I can't look into that issue, unfortunately :(

**Comment by juliushaertl** [comment] 2020-02-26 08:59
> This app is using tiptap for the editor, so I'm assuming the Nextcloud-people didn't make a lot of the design decisions, but yeah, I agree that it seems arbitrary. It's also in tiptap where the left alignment issue is.

tiptap is a renderless library, which means how the UI looks and acts is actually the responsibility of the text app. The modal for the link was actually decided that way together with @jancborchardt .

**Comment by jancborchardt** [comment] 2020-04-01 21:18
Yep, the floating bar could have other inline items as well like bolding and italic next to the link.

Anyhow – that’s a separate discussion. The issue should of course be fixed, and the bar should show properly inside the available viewport. :)

**Comment by azul** [comment] 2020-09-29 11:45
I think this is fixed in NC 20:
* The second menu entry "Link to a file" - made the initial popup wider
* #1045 fixed the remaining.
Closing this for now. Feel free to reopen if it's still showing up in NC 20+

**Closed by azul** 2020-09-29 11:45 UTC
Labels: 1. to develop, bug, design, good first issue
