### ISSUE TITLE
YAML headers, special symbols and table broken => RAW MODE suggested

### ISSUE THREAD

**Issue by robert-winkler** [nextcloud/text#418] opened 2019-11-15 22:13 UTC
**YAML headers and special symbols modified on reading/writing**
For adding document information in markdown documents, YAML headers are common. Those are changed when the markdown files are edited with Text. As well, I noticed the undesired 'optimization' of text, such as [] is changed to \[ \], and \delta becomes \\delta. Additionally, a pipe table becomes modified in my document. This behavior breaks things, e.g., when processing the MD file with Pandoc (<https://pandoc.org/>, <https://peerj.com/articles/cs-112/>). 

**Expected behavior**
Existing markdown code/text should be left unmodified.

**Reproduce - YAML**
1. Create a markdown file with a YAML header
```
---
title: The life of Donald
author: Donald Duck
---
```
2. Upload and modify the file in Nextcloud/Text
3. Download and compare

**Reproduce - Symbols/ Commands**
1. Create a markdown file with special symbols 
```
[@markof_et_al_2019]
$\delta$
```
2. Upload and modify the file in Nextcloud/Text
3. Download and compare

**Reproduce - Table**
1. Create a markdown file with a pipe table
```
| Hello | World |
| ------- | -------- |
| Mick  | 2017   |
```
2. Upload and modify the file in Nextcloud/Text
3. Download and compare

**SUGGESTION**
Provide a RAW MODE option (similar to the previous Markdown Nextcloud editor).

**Comment by nilsbecker** [comment] 2020-06-02 13:56
This appears to be a duplicate of #772

**Closed** 2020-06-02 15:04 UTC
Labels: bug
