### ISSUE TITLE
Can't copy to clipboard in Nextcloud Text

### ISSUE THREAD

**Issue by ztwhaley** [nextcloud/text#1828] opened 2021-08-19 21:12 UTC
**Describe the bug**
Cannot copy to clipboard from Nextcloud Text. 

**To Reproduce**
1. Open up a markdown file to load Nextcloud Text. 
2. Highlight text and select Ctrl + C or right click and select copy. 
3. Try to paste and you will notice that the selected text was not copied.

**Expected behavior**
The copied text should be loaded into clipboard and pasted in the desired location. 

**Client details:**
 - OS: Chrome OS
 - Browser: Chrome
 - Version: 92.0.4515.130
 - Device: Desktop (Pixelbook Go)

<details>
<summary>Server details</summary>

**Text app version:** 3.2.0

**Operating system:** Ubuntu 20.04

**Web server:** Apache

**Database:** mysql 8.0.26

**PHP version:** 7.4.21

**Nextcloud version:** 21.0.3.1

</details>

**Comment by juliushaertl** [comment] 2021-08-20 06:48
Closing as a duplicate of https://github.com/nextcloud/text/issues/1508 but I could never reproduce that so far.

**Closed by juliushaertl** 2021-08-20 06:48 UTC
Labels: bug
