### ISSUE TITLE
Unexpected indent when heading is "Nextcloud"

### ISSUE THREAD

**Issue by thgoebel** [nextcloud/text#3706] opened 2023-01-27 23:42 UTC
**Describe the bug**

Any heading that matches the string "Nextcloud" has an unexpected indent, that is larger than any other heading's indent.

- The matching is case INsensitive, i.e. "NeXtClOuD" triggers the bug as well.
- But it must be exact, i.e. "Nextcloud is great" or "Next cloud" do NOT trigger it.
- Only the first "Nextcloud" heading has too large indent. Subsequent "Nextcloud" headings are indented normally.

**To Reproduce**

1. Create a new .md file
2. Open it in the text app (in the browser, or in the iOS/Android Nextcloud Files apps)
3. Create a heading with string "Nextcloud"

**Expected behavior**

A heading called "Nextcloud" should have the same indent as everything else.

**Screenshots**

![nextcloud-text](https://user-images.githubusercontent.com/33295590/215224892-ee596efb-c4af-44d2-b059-5921d0e060a8.png)

**Client details:**

 - OS: Ubuntu, iOS, Android
 - Client versions:: Firefox 109.0, Nextcloud iOS 4.6.0.19, Nextcloud Android 3.23.1
 - Text app version 3.6.0

<details>
<summary>Server details</summary>

**Text app version:** 3.6.0

**Operating system:** Docker

**Web server:** nginx in front of official Docker image

**Database:** MariaDB

**PHP version:** whatever is in the official Docker image

**Nextcloud version:** 25.0.3

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)

n/a

#### Browser log

n/a

</details>

**Comment by susnux** [comment] 2023-01-27 23:56
Duplicate of https://github.com/nextcloud/text/issues/3513

**Closed by susnux** 2023-01-27 23:56 UTC
Labels: bug

**Comment by thgoebel** [comment] 2023-01-27 23:58
Ah, missed that, sorry.
