### ISSUE TITLE
attach a pdf file to a (Markdown-)text

### ISSUE THREAD

**Issue by mherweg** [nextcloud/text#4724] opened 2023-08-25 09:43 UTC
### Steps to reproduce
1. in NC web GUI create a "text"(.md) File
2. use the attach button to attach a pdf file from server or from Computer
3. close/save this "text" file
4. open it again

### Expected behaviour
when I click on the the pdf preview, the pdf file will open or offered for download

### Actual behaviour
a "broken image" preview - it looks like the pdf is treated like a gif or jpg

### Server configuration
I tried it on 3 different NC Servers, run by 3 different teams. all Linux/docker

NC Version: 27.0.2

**Operating system**:
Debian Linux

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Where did you install Nextcloud from:**

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

### Client configuration
**Browser:**

**Operating system:**

#### Nextcloud log (data/owncloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by juliushaertl** [comment] 2023-11-12 19:13
Will close as a duplicate of https://github.com/nextcloud/text/issues/4723

**Closed** 2023-11-12 19:13 UTC
