### ISSUE TITLE
Enter after headline removes the text

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/text#3150] opened 2022-10-11 09:35 UTC
- Open a document with a headline
- Move the cursor to the end of the headline
- Press Enter
- 💥 The line vanishes

This seems to happen only in Firefox, not Chromium

@susnux Any idea about this? I feel I've seen this happening only after https://github.com/nextcloud/text/pull/2841 so maybe related to the node view, but just a guess.

**Comment by juliushaertl** [comment] 2022-10-11 09:42
Maybe related https://github.com/ueberdosis/tiptap/issues/3200

**Comment by mejo-** [comment] 2022-10-11 11:10
It seems like @susnux already opened an issue upstream at Tiptap: https://github.com/ueberdosis/tiptap/issues/3186

**Comment by susnux** [comment] 2022-10-12 09:49
> It seems like susnux already opened an issue upstream at Tiptap: [ueberdosis/tiptap#3186](https://github.com/ueberdosis/tiptap/issues/3186)

No this is a different issue.

This issue is caused by using a `div` tag inside the `h1` / `h2`... tags which is not allowed and triggers this issue.
It can be fixed by using `span` as the content container.

But there is a different issue (at least on Firefox): Navigating using the arrow keys and pressing enter works, but clicking into the heading and pressing enter will split the heading but also copying the heading anchor link resulting in weird headings.

**Closed** 2022-10-13 05:56 UTC
Labels: bug, high
