### ISSUE TITLE
Image with

### ISSUE THREAD

**Issue by roadfox** [nextcloud/text#816] opened 2020-05-09 14:14 UTC
**Describe the bug**
When inserting an Image the width of the shown image is limited to 130px.

Right now it looks more like a preview of the image, but there is no link or something to see it in full resolution.  And this is wrong all other .md editors show the real Image size and not a preview.

This is due the Image gets contenteditable="false" and this is defined as:

select, button, input, textarea, div[contenteditable="true"], div[contenteditable="false"] {
    **width: 130px;**
    min-height: 34px;
    box-sizing: border-box;
}

**To Reproduce**
1. Create a new textdocument
2. Insert an Image

**Expected behavior**
The Images should be displayed in his native resolution. Limited to the Editor window with.

**Client details:**
 - OS: Ubuntu 16.04
 - Browser: firefox
 - Version: 75.0 (64-Bit)

<details>

Server configuration detail

Operating system: Linux 4.4.0-177-generic #207-Ubuntu SMP Mon Mar 16 01:16:10 UTC 2020 x86_64

Webserver: Apache/2.4.20 (Ubuntu) (cgi-fcgi)

Database: mysql 5.7.30

PHP version: 7.3.17-1+ubuntu16.04.1+deb.sury.org+1

Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, intl, json, exif, msgpack, mysqli, pdo_mysql, apc, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Phar, memcached, Zend OPcache

Nextcloud version: 19.0.0 beta 5 - 19.0.0.6

Updated from an older Nextcloud/ownCloud or fresh install:

Where did you install Nextcloud from: unknown

<details><summary>Signing status</summary>

Array ( )

</details>

<details><summary>List of activated apps</summary>

Enabled:
 - accessibility: 1.5.0
 - activity: 2.12.0
 - admin_audit: 1.9.0
 - audioplayer: 2.10.0
 - bruteforcesettings: 1.6.0
 - calendar: 2.0.3
 - cloud_federation_api: 1.2.0
 - comments: 1.9.0
 - contactsinteraction: 1.0.0
 - dav: 1.15.0
 - deck: 1.0.0
 - federatedfilesharing: 1.9.0
 - federation: 1.9.0
 - files: 1.14.0
 - files_external: 1.10.0
 - files_pdfviewer: 1.8.0
 - files_rightclick: 0.16.0
 - files_sharing: 1.11.0
 - files_trashbin: 1.9.0
 - files_versions: 1.12.0
 - files_videoplayer: 1.8.0
 - firstrunwizard: 2.8.0
 - groupfolders: 6.0.6
 - logreader: 2.4.0
 - lookup_server_connector: 1.7.0
 - mail: 1.3.4
 - music: 0.14.0
 - news: 14.1.7
 - nextcloud_announcements: 1.8.0
 - notes: 3.3.0
 - notifications: 2.7.0
 - oauth2: 1.7.0
 - password_policy: 1.9.0
 - photos: 1.1.0
 - privacy: 1.3.0
 - provisioning_api: 1.9.0
 - recommendations: 0.7.0
 - richdocuments: 3.5.3
 - serverinfo: 1.9.0
 - settings: 1.1.0
 - sharebymail: 1.9.0
 - support: 1.2.0
 - survey_client: 1.7.0
 - systemtags: 1.9.0
 - tasks: 0.12.2
 - text: 3.0.1
 - theming: 1.10.0
 - twofactor_backupcodes: 1.8.0
 - updatenotification: 1.9.0
 - viewer: 1.3.0
 - workflowengine: 2.1.0
Disabled:
 - bookmarks
 - encryption
 - spreed
 - user_ldap

</details>

<details><summary>Configuration (config/config.php)</summary>

{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "19.0.0.6",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "loglevel": 1,
    "forcessl": true,
    "maxZipInputSize": 0,
    "allowZipDownload": true,
    "theme": "",
    "maintenance": false,
    "appcodechecker": false,
    "trusted_domains": [
        "cloud.aironaut.ch",
        "www.cloud.aironaut.ch",
        "localhost",
        "87.237.169.107"
    ],
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trashbin_retention_obligation": "120, auto",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "asset-pipeline.enabled": false,
    "appstore.experimental.enabled": true,
    "appstoreenabled": true,
    "apps_paths": [
        {
            "path": "\/home\/aironaut\/domains\/cloud.aironaut.ch\/public_html\/apps",
            "url": "\/apps",
            "writable": true
        }
    ],
    "memcache.local": "\\OC\\Memcache\\APCu",
    "overwrite.cli.url": "https:\/\/cloud.aironaut.ch",
    "mysql.utf8mb4": true,
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "25",
    "updater.release.channel": "beta",
    "app_install_overwrite": [
        "news",
        "issuetemplate",
        "spreed"
    ]
}

</details>

External storages: yes

<details><summary>External storage configuration</summary>

No mounts configured

</details>

Encryption: no

User-backends:

    OC\User\Database

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0

</details>

**Comment by juliushaertl** [comment] 2020-05-14 12:13
Duplicate of https://github.com/nextcloud/text/issues/662

**Closed by juliushaertl** 2020-05-14 12:13 UTC
Labels: bug
