### ISSUE TITLE
Code-Signing issue after Nextcloud upgrade

### ISSUE THREAD

**Issue by Lamera** [nextcloud/text#422] opened 2019-11-18 11:25 UTC
**Describe the bug**
I was upgrading from Nextcloud 16 to Nextcloud 17.0.1. After the upgrade Nextcloud complained about the added files from text.

**To Reproduce**
1. Install Nextcloud 16
2. Install the app "text"
3. Upgrade Nextcloud to the latest version
4. Go to settings > overview
5. See the error of Code Signing

**Expected behavior**
A smooth upgrade without exceptions.

<details>
<summary>Server details</summary>

**Text app version:**
1.1.1

**Operating system:**
Ubuntu Server 18.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7

**Nextcloud version:**
17.0.1

</details>

<details>
<summary>Logs</summary>

#### Nextcloud list of failed integrity
```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- text
	- EXTRA_FILE
		- .github/pull_request_template.md
		- .github/ISSUE_TEMPLATE/Bug_report.md
		- .github/ISSUE_TEMPLATE/Feature_request.md
		- .eslintrc.js
		- README.md
		- .tx/config
		- .gitattributes
		- .l10nignore
		- package-lock.json
		- l10n/.gitkeep
		- package.json

Raw output
==========
Array
(
    [text] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [.github/pull_request_template.md] => Array
                        (
                            [expected] => 
                            [current] => 9307a7ab3b06266ccda57e66ae678b31db3faf26a51c508d60b9bc2874ed59d46bcd1c1d07970e2af0947f826f050f953cbf02a962a4b40cb1572f5fcd8f94a1
                        )

                    [.github/ISSUE_TEMPLATE/Bug_report.md] => Array
                        (
                            [expected] => 
                            [current] => 2a574514bba022a69c723616091bfd19eb5b4821aef95846eb942e90ee80cf2b2b8710091660fc99b43eb922b47d96f89b4e38c72d14909d76a9c88edbe7a28b
                        )

                    [.github/ISSUE_TEMPLATE/Feature_request.md] => Array
                        (
                            [expected] => 
                            [current] => 84541137d4035e61148e33f0560e8f96c2dffde247b672459cf45f32c57bcfb6a4479dcf9c45b6598e95f61369bfad2d16c7784d59a689ad46c7b332216f891b
                        )

                    [.eslintrc.js] => Array
                        (
                            [expected] => 
                            [current] => 74262fe75f2c990b21f1116e86083b5ec635a084a3c3cba8ef7cf62f6ea398ed5f1b94c770a230993273a7bd2ff1587106b778814331e4bf6c0e20b82340bc94
                        )

                    [README.md] => Array
                        (
                            [expected] => 
                            [current] => ec0ad73e49149bc6200d8b07cc14a6795936d6c150ad20d30c9d694ea6ebe4b4738f81fc50d1f84d68d0c62e045f1b854ab56a1264b9310aadb2aa54a7573194
                        )

                    [.tx/config] => Array
                        (
                            [expected] => 
                            [current] => 80dfc72f84d02213d63b236925f020fc21f17fc5d1964cd84c0530fb65f3738cd03ff923f50ba8396d5832f5a04276891733281ecba82321cb426f13aa968516
                        )

                    [.gitattributes] => Array
                        (
                            [expected] => 
                            [current] => da176baa1edf0a8408ffa35e07849a980e68fe0dd5f53569e583aec2e362f61d47e1ff6968d2fd92787b59ee2f8f38cbe8dcdde7e3ef1e24081cd21dc61e1d30
                        )

                    [.l10nignore] => Array
                        (
                            [expected] => 
                            [current] => 3a07b78d317a75ec5a027b869771b5464be4749f645e8e9e1999864c710ce5b115279bd159758addcf0bcd182e28da35da0156c5ff43af69bb869e5225818f98
                        )

                    [package-lock.json] => Array
                        (
                            [expected] => 
                            [current] => 851dfbb766522728bdb6b468b02e4f3bd8a5f481c1ce89c7d151764b8ec0c35344032d771b8bb94b3e99f6e625c580c41eb3e480166d165731039f6de2e002c4
                        )

                    [l10n/.gitkeep] => Array
                        (
                            [expected] => 
                            [current] => cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e
                        )

                    [package.json] => Array
                        (
                            [expected] => 
                            [current] => fec4073b810d23b3b314e58c1ba6c40f12f429fb623998685d65f93e5afc45f7ddc91d8467e905b00536c091ed3f5395b054f01df8d2f0dd6d213442d1241b11
                        )

                )

        )

)


```

</details>

**Comment by pieter-groeneweg** [comment] 2019-11-18 15:31
Same here....  though on debian7, apache 2.4 mysql10.1.41, PHP7.2

**Comment by Snousmoumryk** [comment] 2019-11-18 17:08
Confirm the issue
Upgrade path 16.0.6->17.0.1

> - text
> 	- EXTRA_FILE
> 		- package-lock.json
> 		- package.json
> 		- .github/ISSUE_TEMPLATE/Feature_request.md
> 		- .github/ISSUE_TEMPLATE/Bug_report.md
> 		- .github/pull_request_template.md
> 		- .tx/config
> 		- .l10nignore
> 		- .gitattributes
> 		- README.md
> 		- l10n/.gitkeep
> 		- .eslintrc.js

**Comment by fuzunspm** [comment] 2019-11-18 20:22
very same issue here

**Comment by pwyde** [comment] 2019-11-18 21:02
I can also confirm.
Upgrade path 16.0.5 --> 17.0.1

**Comment by nightcat91** [comment] 2019-11-19 12:12
Same issue here 
Upgrade from 16.0.1 to 17.0.1 on Debian 9

I cant seem to find the files mentioned... if anybody knows where they can be found I would gladly try to remove them

**Comment by obnoxious23** [comment] 2019-11-19 13:37
Same issue, 16.0.5 --> 17.0.1 on Debian stable

**Comment by pieter-groeneweg** [comment] 2019-11-19 18:53
anyone around that at least can give some statement on what we can do now?
do we need to uninstall and reinstall?
can we safely delete those extra files?

**Comment by Snousmoumryk** [comment] 2019-11-19 20:01
> can we safely delete those extra files?

Yes, we can safely to get rid of them.
Just follow the list of files and double check their date.

There is another test NC instance in my environment, with different upgrade path.
And at NC 17.0.1 there are NO files from above list in it.

**Comment by pwyde** [comment] 2019-11-20 10:12
> 
> 
> > can we safely delete those extra files?
> 
> Yes, we can safely get rid of them.
> Just follow the list of files and double check their date.
> 
> There is another test NC instance in my environment, with different upgrade path.
> And at NC 17.0.1 there are NO files in it from above list.

I can confirm that the error message disappears after deleting the listed files in `nextcloud/apps/text/`. Thank you!

**Comment by pieter-groeneweg** [comment] 2019-11-20 11:40
> I can confirm that the error message disappears after deleting the listed files in `nextcloud/apps/text/`. Thank you!

And "Text" still functions without problems after?

**Comment by pwyde** [comment] 2019-11-20 11:43
> 
> 
> > I can confirm that the error message disappears after deleting the listed files in `nextcloud/apps/text/`. Thank you!
> 
> And "Text" still functions without problems after?

Yes. Tested editing a .txt file directly after and it worked on my NC instance. 😄

**Comment by Lamera** [comment] 2019-11-21 06:00
I can confirm this too.
Ran this command: rm .github/pull_request_template.md .github/ISSUE_TEMPLATE/Bug_report.md .github/ISSUE_TEMPLATE/Feature_request.md .eslintrc.js README.md .tx/config .gitattributes .l10nignore package-lock.json l10n/.gitkeep package.json 

Afterwards text is working as intended. Why were there such github files in it?

**Comment by expressrussian** [comment] 2019-11-23 19:26
Confirm the issue. 16.0.5 --> 17.0.1
First, i got the HTTP error 500. Had to seek a special occ command to finish the update.
Now [Text]. And this is "Official" application! 
What a messy upgrade to 17.0.1!!!

**Comment by juliushaertl** [comment] 2019-11-25 15:01
Closing as this is a duplicate of https://github.com/nextcloud/server/issues/16939

The workaround to delete the leftover files it totally right:

```
rm .github/pull_request_template.md .github/ISSUE_TEMPLATE/Bug_report.md .github/ISSUE_TEMPLATE/Feature_request.md .eslintrc.js README.md .tx/config .gitattributes .l10nignore package-lock.json l10n/.gitkeep package.json
```

**Closed by juliushaertl** 2019-11-25 15:01 UTC
Labels: bug
