### ISSUE TITLE
Failed to load file

### ISSUE THREAD

**Issue by softweb-dev** [nextcloud/text#3690] opened 2023-01-21 22:45 UTC
" Failed to load file,  This file cannot be displayed as download is disabled by the share " issue is showing if " hide download" is active.

**Comment by Pilzinsel64** [comment] 2023-01-25 16:08
True, same here, I ad to update all my links.
Is that indeed or is that a bug?

**Comment by luka-nextcloud** [comment] 2023-01-25 16:37
@softweb-dev I think the issue is not well explained, could you please elaborate?

**Comment by softweb-dev** [comment] 2023-01-25 19:13
Its bug for shure. I have also tested with a fresh installation. Same issues. Its because old Javascript code inside the app. Developer will fix that next version.

**Comment by softweb-dev** [comment] 2023-01-25 19:18
> True, same here, I had to update all my public links. Is that indeed or is that a bug?

Its Bug.

**Comment by luka-nextcloud** [comment] 2023-01-26 13:05
@softweb-dev I cannot see the image.

![image](https://user-images.githubusercontent.com/89908051/214842741-628dfdbc-7044-4faf-a688-575cddac4f42.png)

**Comment by luka-nextcloud** [comment] 2023-01-30 13:22
@softweb-dev I cannot reproduce as you can see from the video, could you share a screen recording?

https://user-images.githubusercontent.com/89908051/215489126-2bc7ac18-622c-433a-be27-715f2e6a2419.mov

**Comment by Pilzinsel64** [comment] 2023-01-31 07:40
@luka-nextcloud You need to open the file via the public link:
https://user-images.githubusercontent.com/23138465/215696726-14624f4e-9800-4ea0-827b-5a7340fd8a71.mov

**Comment by Pilzinsel64** [comment] 2023-02-01 11:47
Related: #3704

**Comment by whenthelight** [comment] 2023-02-02 18:12
> @luka-nextcloud You need to open the file via the public link: https://user-images.githubusercontent.com/23138465/215696726-14624f4e-9800-4ea0-827b-5a7340fd8a71.mov
> 
> It worked just fine with v25.0.2 or v25.0.1 (not sure the last working version yet, probably I regoniced it too late).

Same Error @my Installation. V25.0.1 worked fine. 
After Update to V25.0.3 this Error happened. Another Instance with V25.0.2 also have this Error. Public Share with "Hide Download" and marked as editable.

**Comment by juliushaertl** [comment] 2023-02-02 22:24
I've commented in https://github.com/nextcloud/text/issues/3704 with the reference on how this could be fixed. Will close this one as a duplicate of #3704

**Closed by juliushaertl** 2023-02-02 22:24 UTC
Labels: bug
