### ISSUE TITLE
[Bug]: Read only shared text file is not up-to-date with saved file

### ISSUE THREAD

**Issue by niowniow** [nextcloud/text#2388] opened 2022-05-12 12:23 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Offline edits of a shared text file (shared as non-editable) which are then synced are not updated in the in-browser view of the shared file

### Steps to reproduce

1. create a text file in nextcloud
2. edit it with the in built-in text editor
3. share the next file via public link without allowing editing
4. sync the file using the desktop client
5. edit synced file offline
6. sync again
7. the shared document does not show the changes
8. open the file in the nextcloud text editor
The warning appears:
![image](https://user-images.githubusercontent.com/5802846/168067392-73c55722-41a8-4823-9e3c-f1397f401d98.png)
and I can choose "use current version" or "use saved version". 
9. Clicking "use saved version" updates the shared file

### Expected behavior

Any changes to the file saved in the nextcloud are reflected in the shared file. The saved text file (i.e. the file that is in the nextcloud filesystem) is shown in the shared in-browser text file view, not any other version that may be in some cache of the nextcloud text editor (or somewhere else).

### Installation method

Other

### Operating system

Other

### PHP engine version

Other

### Web server

Other

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
I don't have access to the command-line
```

### Additional info

hosted by webo.hosting

**Comment by mejo-** [comment] 2022-11-01 13:38
Dear @niowniow, thanks for your report. I was able to reproduce the behaviour that you describe.

The problem is that the editor session of the shared file is not cleaned up when closing the tab. So when opening the share link again fast enough (with the file having been altered via file sync in the meantime), the version from the session and the file as stored in Nextcloud differ and the conflict dialog is displayed.

We definitely should improve user experience here. I wonder whether we could detect that the file in session had been written to the filesystem and thus any subsequent changes are legit newer versions of the file.

@max-nextcloud as you're working on this field at the moment.

**Comment by juliushaertl** [comment] 2022-11-02 11:50
Code wise this seems to be related to the check to only reset the document when no active sessions are there in https://github.com/nextcloud/text/blob/f5a34ceef75ce5e234bc8275b84ada6ca22c563e/lib/Service/ApiService.php#L93-L97

**Comment by s4069b** [comment] 2023-10-10 06:33
I have reproduced the same bug.

**Comment by meonkeys** [comment] 2023-10-10 18:46
> I have reproduced the same bug.

Thanks. Just hit the thumbs-up emoji at the bottom of the original description unless you have details to add.

**Comment by UllisHellfireeXperiments** [comment] 2023-12-10 14:55
The same behavior is observable also when changing a file with the Notes app, with the same message being issued by the Text Editor: "The document has been changed outside of the file editor. The changes cannot be applied."

**Comment by max-nextcloud** [comment] 2024-07-10 07:44
Idea: When connecting to a read only document:
* check if there is an exising editing session
* if there is one connect to it
* otherwise render the content statically and check back a minute later.

**Comment by max-nextcloud** [comment] 2024-07-24 13:06
For now #6094 fixes two related bugs:
* Cleanup sessions for plain text documents if the file was overwritten.
* Hide conflict dialogue in read only mode.

This does not get us all the way there - as the content is not automatically updated.
But at least it gets rid of the unusable conflict resolution dialogue.
If there's an actual conflict there's not much we can do - but if there's none we at least display a `Reload` button now.

**Closed** 2024-07-24 16:26 UTC
Labels: bug, 2. developing, feature: conflict resolution, high
