### ISSUE TITLE
Window not resizing to full after closing sidebar

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/text#522] opened 2020-01-07 08:51 UTC
_latest master of 18 and Text_

**To Reproduce**
1. Open a document in Text
2. Click on the _Open Sidebar_ button > sidebar opens
3. Click on the sidebar's _close_ button
4. see sidebar closing

**Expected behavior**
Text window resizes to full width

**Actual behavior**
Text window does not resize

**Screenshots**
![Peek 2020-01-07 09-46](https://user-images.githubusercontent.com/1804221/71881717-2316a080-3133-11ea-8234-8628109e712f.gif)

**Comment by skjnldsv** [comment] 2020-01-07 09:32
duplicate of https://github.com/nextcloud/files_pdfviewer

**Closed by skjnldsv** 2020-01-07 09:32 UTC
Labels: bug

**Comment by wiswedel** [comment] 2020-01-07 09:47
Those meta-repos suck
