### ISSUE TITLE
No way to undo headline formating

### ISSUE THREAD

**Issue by schiessle** [nextcloud/text#5217] opened 2024-01-09 17:58 UTC
If you write a text with some headlines and later want to revert a headline to normal text there is no way beside deleting the line and write it again.

All other formatting options can be undo by clicking it again (bold, italic, bullet points,...). For headlines I only have the option to chose another headline level but not to go back to "normal text":

![image](https://github.com/nextcloud/text/assets/1589737/ec536470-be65-4777-862b-bb3b294cbd6f)

**Comment by juliushaertl** [comment] 2024-01-09 19:33
You can untoggle the heading by just selecting the same heading level from the menu. We used to have a button to reset to paragraph but that was removed during a design review iirc.

cc @nextcloud/designers

**Comment by marcoambrosini** [comment] 2024-01-10 12:30
I think something akin to "paragraph" should definitely be in that menu, along with all other text styles such as quote, code block, etc.  
This would:
* Clear up space in the toolbar
* Make those functionalities clearer because those buttons would be labeled

**Comment by juliushaertl** [comment] 2024-01-10 16:29
The problem is that the trigger button for the menu currently indicates the state of the current cursor. If we add more entries to that and still use that indication the headline actions would be too hidden i think.

**Comment by marcoambrosini** [comment] 2024-01-10 16:36
What about adding a label like Notion so that it's clearer that text styles and other blocks are underneath that menu? I think there would be a lot to gain from this simplification. Especially given the current amount of unlabeled buttons.

**Comment by juliushaertl** [comment] 2024-01-10 16:56
I think this is something where some mockups could help to visualize how that could fit in the current UI. Especially on mobile we are quite limited on how much space we have there.

**Comment by juliushaertl** [comment] 2024-01-10 19:11
Also https://github.com/nextcloud/text/issues/2836 might have a few points to consider when thinking about redesigning the menu bar.

**Comment by szaimen** [comment] 2024-01-11 08:41
So in my opinion actually the chosen Headline should be selected so that if you click on it, it gets unselected, something like this:

| H2 selected | No headline selected |
|---|---|
| ![image](https://github.com/nextcloud/text/assets/42591237/42fbfbf9-72c0-4c66-a382-7cbb64eefc38) | ![image](https://github.com/nextcloud/text/assets/42591237/a104c807-744f-473f-a083-08d028419a4c) |

**Comment by marcoambrosini** [comment] 2024-01-11 08:47
@szaimen as a quick fix, yes that would work. But I'd still think that it would be nicer to have a text "styles" menu.

**Comment by ckoegler** [comment] 2024-10-28 21:56
If I format a paragraph to a H1 I cannot undo it via Ctrl+Z.
In contrast, it works for other formattings (e.g. from plain text do bold)

**Comment by mejo-** [comment] 2024-10-30 15:05
> If I format a paragraph to a H1 I cannot undo it via Ctrl+Z.

Dear @ckoegler, thanks for the report. Which Nextcloud version do you run? I'm unable to reproduce your problem. Given that it's not related to the topic discussed here, please open a new issue about it.

**Comment by mejo-** [comment] 2024-10-30 15:06
Let's close this issue for now, as we have clear indicators nowadays that show the enabled headline formatting with a checkmark.

**Closed by mejo-** 2024-10-30 15:06 UTC
Labels: enhancement, design
