### ISSUE TITLE
extra line shown trailing code block

### ISSUE THREAD

**Issue by brainchild0** [nextcloud/text#869] opened 2020-06-14 06:08 UTC
# Description

Editing buffer adds empty line to code block compared to document file.

# Steps to reproduce

1. Copy [example file](https://gist.githubusercontent.com/brainchild0/d2abd3a37158e9808064f8c3285c927b/raw/630ecc279792a9e711cff3a73f5705f949a15a64/hello_world.md) to Nextcloud instance.
1. Verify that code block has no empty lines.
1. Open file in application.
    *Notice extra line at end of  code block.*

# Screenshots

![Screenshot from 2020-06-14 02-04-14](https://user-images.githubusercontent.com/34869175/84586028-af647800-ade3-11ea-93f8-97c4b96f57c7.png)

# Client details
 - OS: Linux Mint 19.3
 - Browser: Firefox
 - Version: 77.0.1
 - Device: Desktop

# Server details

<details>
<summary>Server details</summary>

Server configuration detail

Operating system: Linux 3.10.0-962.3.2.lve1.5.33.el7.x86_64 #1 SMP Fri Mar 13 09:20:40 EDT 2020 x86_64

Webserver: Apache (fpm-fcgi)

Database: mysql 10.2.31

PHP version:

7.3.18 Modules loaded: Core, date, libxml, openssl, pcre, zlib, bz2, calendar, ctype, hash, filter, ftp, gettext, gmp, SPL, iconv, Reflection, session, standard, SimpleXML, sockets, mbstring, tokenizer, xml, cgi-fcgi, mysqlnd, apcu, bcmath, curl, dba, dom, enchant, fileinfo, gd, i360, imagick, imap, intl, json, ldap, exif, mysqli, odbc, PDO, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, pspell, redis, soap, sodium, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, xmlreader, xmlrpc, xmlwriter, xsl, zip, ionCube Loader, Zend OPcache

Nextcloud version: 19.0.0 - 19.0.0.12

Updated from an older Nextcloud/ownCloud or fresh install:

Where did you install Nextcloud from: unknown
Signing status
Array ( )
List of activated apps
``` Enabled: - accessibility: 1.5.0 - activity: 2.12.0 - admin_audit: 1.9.0 - apporder: 0.10.0 - audioplayer: 2.10.0 - bookmarks: 3.1.1 - calendar: 2.0.3 - checksum: 0.4.4 - cloud_federation_api: 1.2.0 - comments: 1.9.0 - contacts: 3.3.0 - contactsinteraction: 1.0.0 - dav: 1.15.0 - encryption: 2.7.0 - external: 3.6.0 - federatedfilesharing: 1.9.0 - federation: 1.9.0 - files: 1.14.0 - files_external: 1.10.0 - files_markdown: 2.3.0 - files_pdfviewer: 1.8.0 - files_rightclick: 0.16.0 - files_sharing: 1.11.0 - files_trashbin: 1.9.0 - files_versions: 1.12.0 - files_videoplayer: 1.8.0 - firstrunwizard: 2.8.0 - issuetemplate: 0.6.0 - logreader: 2.4.0 - lookup_server_connector: 1.7.0 - mail: 1.3.5 - metadata: 0.11.1 - news: 14.1.11 - nextcloud_announcements: 1.8.0 - notes: 3.5.1 - notifications: 2.7.0 - oauth2: 1.7.0 - passman: 2.3.5 - password_policy: 1.9.1 - passwords: 2020.6.0 - photos: 1.1.0 - previewgenerator: 2.3.0 - privacy: 1.3.0 - provisioning_api: 1.9.0 - qownnotesapi: 20.1.0 - quota_warning: 1.8.0 - recommendations: 0.7.0 - serverinfo: 1.9.0 - settings: 1.1.0 - sharebymail: 1.9.0 - social: 0.2.101 - support: 1.2.1 - survey_client: 1.7.0 - systemtags: 1.9.0 - tasks: 0.13.1 - text: 3.0.1 - theming: 1.10.0 - twofactor_backupcodes: 1.8.0 - updatenotification: 1.9.0 - user_ldap: 1.9.0 - viewer: 1.3.0 - workflowengine: 2.1.0 Disabled: ```
Configuration (config/config.php)
``` { "instanceid": "***REMOVED SENSITIVE VALUE***", "passwordsalt": "***REMOVED SENSITIVE VALUE***", "secret": "***REMOVED SENSITIVE VALUE***", "trusted_domains": [ "nextcloud.ericlevy.name" ], "datadirectory": "***REMOVED SENSITIVE VALUE***", "dbtype": "mysql", "version": "19.0.0.12", "overwrite.cli.url": "https:\/\/nextcloud.ericlevy.name", "dbname": "***REMOVED SENSITIVE VALUE***", "dbhost": "***REMOVED SENSITIVE VALUE***", "dbport": "", "dbtableprefix": "oc_", "dbuser": "***REMOVED SENSITIVE VALUE***", "dbpassword": "***REMOVED SENSITIVE VALUE***", "installed": true, "maintenance": false, "mail_from_address": "***REMOVED SENSITIVE VALUE***", "mail_smtpmode": "smtp", "mail_sendmailmode": "smtp", "mail_domain": "***REMOVED SENSITIVE VALUE***", "mail_smtpauthtype": "LOGIN", "mail_smtpauth": 1, "theme": "", "loglevel": 2, "mysql.utf8mb4": false, "updater.release.channel": "beta", "ldapIgnoreNamingRules": false, "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory", "app_install_overwrite": [ "social", "checksum", "contacts", "apporder", "external", "files_markdown", "passman", "quota_warning", "issuetemplate" ], "updater.secret": "***REMOVED SENSITIVE VALUE***" } ```

Are you using external storage, if yes which one: local/smb/sftp/...

Are you using encryption: 1

Are you using an external user-backend, if yes which one: LDAP/ActiveDirectory/Webdav/...
LDAP configuration (delete this par if not used)

</details>

**Comment by juliushaertl** [comment] 2020-06-16 06:44
I can reproduce that, it seems like this is mainly due to the way we transfer markdown into the editor where the trailing newline from markdown-it gets interpreted as a new line in the html output:

![image](https://user-images.githubusercontent.com/3404133/84740401-9b6c7200-afad-11ea-8e9c-74f2c4316df9.png)

**Comment by arnowelzel** [comment] 2020-08-02 05:27
I can confirm this as well. The result is with an extra `<br>` in the output:

Markdown input (shown with ''' as substitude for backticks):

```
'''
Some text
'''
```

HTML output:

```
<pre><code>
Some Text
<br>
</code></pre>
```

**Comment by claell** [comment] 2021-03-13 11:35
Looks like a duplicate of #150, so marking and closing.

**Comment by claell** [comment] 2021-03-13 11:36
Duplicate of #150

**Closed by claell** 2021-03-13 11:36 UTC
Labels: 1. to develop, bug
