### ISSUE TITLE
Text changed the language of the markdown file

### ISSUE THREAD

**Issue by hrv231** [nextcloud/text#1656] opened 2021-06-15 23:40 UTC
**Describe the bug**
When using Nextcloud Notes with a file, and create lists using dashes [-] instead of the [*], the files editor reconfigure the - into * after saving it with the nextcloud text editor.

**To Reproduce**
1. Create a .md file for test.
2. Edit the file and create lists using dashes.
3. Save the file and open it via Files.
4. After opening the file via Files, edit one item from the list, then do Ctrl+S.
5. Go to Nextcloud Notes and edit the file, this time will appear with all item from the list with * instead of the previous -

**Expected behavior**
No changes to a Markdown file that uses dashes[ - ] for lists instead of star[ * ] .

**Screenshots**
Create a list with dashes using Nextcloud Notes
![image](https://user-images.githubusercontent.com/41212308/122136535-8bbd7e80-cdf7-11eb-89da-5b20badcf8c8.png)
Edit one item from the list with Nextcloud native editor, and save the file.
![image](https://user-images.githubusercontent.com/41212308/122136592-a3950280-cdf7-11eb-90ff-51529156aee9.png)
Open the file again with Nextcloud Notes, and all items from the list now have stars instead of dashes.
![image](https://user-images.githubusercontent.com/41212308/122136624-b3144b80-cdf7-11eb-8974-133a20685d03.png)

**Client details:**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 89.0
 - Device: desktop

<details>
<summary>Server details</summary>

**Text app version:** 2.14.0

**Operating system:** Docker

**Web server:**

**Database:** mysql Ver 15.1 Distrib 10.4.19-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**PHP version:**

**Nextcloud version:** 20.0.8

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by korelstar** [comment] 2021-06-17 00:30
Duplicate of #593

**Closed by korelstar** 2021-06-17 00:30 UTC
Labels: bug
