### ISSUE TITLE
link in md file to NC related stuff like @user, +label, ...

### ISSUE THREAD

**Issue by DarkknightAK** [nextcloud/text#502] opened 2019-12-30 09:29 UTC
In github or any chat app you can with type @user to ping an user or add the stuff together.

It would be glade if you can use this kind of stuff in an markdown file (or in all the different NC apps like chat, mail, kanban, todo, ...) AND also in the description area of each single file.

The result for me would be to have an README.md file in the project folder where I can write description stuff but also add users, describe which labels are used, ...

**Comment by juliushaertl** [comment] 2019-12-30 09:33
> In github or any chat app you can with type @user to ping an user or add the stuff together.

Duplicate of #92 

> It would be glade if you can use this kind of stuff in an markdown file (or in all the different NC apps like chat, mail, kanban, todo, ...) AND also in the description area of each single file.

This is a bit vague. I'll close this ticket as the mentioning is a duplicate and the readme file functionality is coming. Feel free to open new request with a more differenciated description for this.

> The result for me would be to have an README.md file in the project folder where I can write description stuff but also add users, describe which labels are used.

Part of rich workspaces coming with 18.

**Closed by juliushaertl** 2019-12-30 09:33 UTC
Labels: enhancement

**Comment by DarkknightAK** [comment] 2019-12-30 09:53
Thanks for the feedback. I will have a look what will come with 18.
