### ISSUE TITLE
Add comment to specific selected text in document

### ISSUE THREAD

**Issue by eviawriter** [nextcloud/text#525] opened 2020-01-08 13:28 UTC
**Is your feature request related to a problem? Please describe.**
I would like to be able to share a document where others can comment on specific sections or words in the text. Preferably they also are not able to edit the document directly, but can only add comments to specific words or text blocks.   

This is great when you only need people to review your document, but don't want them to edit the document directly.   

**Describe the solution you'd like**
A commenter selects the text he or she wants to comment on. A pop-up adds the option to add a comment. The person who shared the document, can read the comment by hovering over the commented text, or by clicking on the comment in the comment-section of the right-hand bar. 

**Describe alternatives you've considered**
Dropbox Paper gives you this option. You share the document with other people. They can add comments when they select specific texts in the document. The person who shared the document can read these comments.  

**Additional context**
![example](https://user-images.githubusercontent.com/38635700/71981260-4f5d1a80-3222-11ea-940e-669b295083c2.png)

**Comment by mejo-** [comment] 2022-04-12 10:42
Closing this as a duplicate of #185.

**Closed by mejo-** 2022-04-12 10:42 UTC
Labels: enhancement
