### ISSUE TITLE
Editing markdown source

### ISSUE THREAD

**Issue by pico40** [nextcloud/text#815] opened 2020-05-09 11:12 UTC
**Is your feature request related to a problem? Please describe.**
I like to manipulate markdown code instead of just seeing the rendered result in a WYSIWYG editor.

**Describe the solution you'd like**
I would like to have a button or tabs (like on github) to switch between a source editor and a WYSIWYG editor.

**Describe alternatives you've considered**
An alternative would be two have two completely different editors.

**Comment by juliushaertl** [comment] 2020-05-14 11:34
Duplicate of #123 

https://github.com/nextcloud/text/issues/123#issuecomment-508723049

**Closed by juliushaertl** 2020-05-14 11:34 UTC
Labels: enhancement
