### ISSUE TITLE
Unwelcome Line Breaks Added to Files 

### ISSUE THREAD

**Issue by alderson59** [nextcloud/text#1204] opened 2020-11-25 19:03 UTC
**Describe the bug**
Linebreaks are added to .md files where there shouldn't be any

**To Reproduce**
1. Type text like this in any basic editor
![image](https://user-images.githubusercontent.com/69715968/100270134-923af480-2f92-11eb-94c8-a1fc41ee72fe.png)
2. Paste into NC Text
![image](https://user-images.githubusercontent.com/69715968/100270278-cf06eb80-2f92-11eb-9142-da810c0e96ac.png)

3. Select all and copy content from within NC Text
![image](https://user-images.githubusercontent.com/69715968/100270338-e219bb80-2f92-11eb-9a69-62313d8eaf97.png)

4. Paste into any basic text editor
![image](https://user-images.githubusercontent.com/69715968/100270374-ee9e1400-2f92-11eb-8eae-aef1019e7e4e.png)

5. New line breaks!

**Expected behavior**
No extra line breaks added

**Client details:**
 - OS: Windows
 - Browser: Chrome
 - Version: 87.0.4280.66
 - Device: Desktop

<details>
<summary>Server details</summary>

**Text app version:** 
3.1.0

**Operating system:** 
Ubuntu 20.0.4

**Web server:** 
docker - nextcloud:20.0.0-apache

**Database:**
docker - mariadb:10.4

**Nextcloud version:** (see Nextcloud admin page)
NC20

</details>

**Comment by claell** [comment] 2021-03-13 11:28
This is most likely having the same root cause as #593, so closing this and marking as duplicate. Please follow up there (and comment here if I am wrong).

**Comment by claell** [comment] 2021-03-13 11:29
Duplicate of #593

**Closed by claell** 2021-03-13 11:29 UTC
Labels: bug
