### ISSUE TITLE
Table support

### ISSUE THREAD

**Issue by themedleb** [nextcloud/text#883] opened 2020-06-17 06:23 UTC
Please add markdown table support, that's the only major feature missing that I can see.
And for the solution, I'm sorry I don't have much experience in Markdown.

**Comment by themedleb** [comment] 2020-06-17 06:43
I did have a look at the Tiptap project which this project (Text) is based on, and found out that Tables are supported https://tiptap.scrumpy.io/tables, so I think it should be easier than starting from scratch.

Thank you for the awesome efforts.

**Comment by juliushaertl** [comment] 2020-06-17 06:52
Duplicate of #114

**Closed by juliushaertl** 2020-06-17 06:52 UTC
Labels: enhancement

**Comment by themedleb** [comment] 2020-06-17 07:04
Oh, sorry, thank you for letting me know.
