### ISSUE TITLE
Blank Lines Removed On Save

### ISSUE THREAD

**Issue by cwmke** [nextcloud/text#902] opened 2020-06-22 15:32 UTC
### Steps to reproduce
1. Create a new file.
2. Copy and paste the text from above.
3. Add a blank line between lines 2 and 3.
4. Confirm changes were saved.
5. Close and reopen the file.

### Expected behaviour
Blank lines still exist upon reopening the file.

### Actual behaviour
After entering a blank line underneath some text, after closing and reopening, the blank line is gone.

~~~
Blah Blah Blah
Blah Blah Blah

Blah Blah Blah
~~~

Becomes

~~~
Blah Blah Blah
Blah Blah Blah
Blah Blah Blah
~~~

## Server configuration detail

**Operating system:** Fedora Linux 5.6.18-200.fc31.x86_64 #1 SMP Wed Jun 10 22:18:55 UTC 2020 x86_64

**Webserver:** Apache/2.4.43 (Fedora) OpenSSL/1.1.1g mod_perl/2.0.11 Perl/v5.30.3 (fpm-fcgi)

**Database:** pgsql PostgreSQL 11.8 on x86_64-redhat-linux-gnu, compiled by gcc (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2), 64-bit

**PHP version:** 

7.3.18
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, gd, gmp, iconv, intl, json, exif, mysqlnd, PDO, pgsql, Phar, posix, shmop, SimpleXML, soap, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlwriter, mcrypt, mysqli, pdo_mysql, pdo_pgsql, pdo_sqlite, xmlreader, xmlrpc, apcu, geoip, igbinary, imagick, msgpack, zip, redis, Zend OPcache

**Nextcloud version:** 18.0.6 - 18.0.6.0

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - admin_audit: 1.8.0
 - apporder: 0.10.0
 - bruteforcesettings: 1.6.0
 - calendar: 2.0.3
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - contacts: 3.3.0
 - dav: 1.14.0
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_downloadactivity: 1.7.0
 - files_markdown: 2.3.0
 - files_pdfviewer: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - geoblocker: 0.3.1
 - impersonate: 1.5.2
 - issuetemplate: 0.6.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - metadata: 0.11.1
 - nextcloud_announcements: 1.7.0
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - password_policy: 1.8.0
 - photos: 1.0.0
 - previewgenerator: 2.3.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - recommendations: 0.6.0
 - richdocuments: 3.7.0
 - riotchat: 0.4.3
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - spreed: 8.0.9
 - survey_client: 1.6.0
 - systemtags: 1.8.0
 - tasks: 0.13.1
 - telephoneprovider: 1.0.3
 - text: 2.0.0
 - theming: 1.9.0
 - theming_customcss: 1.6.0
 - twofactor_backupcodes: 1.7.0
 - twofactor_totp: 4.1.3
 - updatenotification: 1.8.0
 - viewer: 1.2.0
 - workflowengine: 2.0.0
Disabled:
 - circles
 - deck
 - encryption
 - end_to_end_encryption
 - external
 - files_external
 - notes
 - ransomware_detection
 - ransomware_protection
 - socialsharing_email
 - support
 - user_ldap

```
</details>

## Client configuration

**Browser:** Brave 1.9.80 Chromium: 81.0.4044.138 (Official Build) (64-bit)

**Operating system:** Fedora

**Comment by juliushaertl** [comment] 2020-06-22 17:57
I cannot see any issues. Are you referring to a markdown or plain text file? Do you enter a regular line break (Shift+Enter) or a new paragraph (Enter)?

**Comment by cwmke** [comment] 2020-06-23 00:49
Using a markdown file. I didn't realize there were different line breaks but I just tested out Shift+Enter with the same result. Console shows the below errors.

~~~
moment is deprecated: please ship your own, this will be removed in Nextcloud 20
ne @ globals.js:64
get @ globals.js:64
updateLastSavedStatus @ editor.js?v=c6b0ddec2a366704250b:108
(anonymous) @ editor.js?v=c6b0ddec2a366704250b:108
~~~

~~~
Failed to load resource: the server responded with a status of 404 (Not Found) - https://REDACTED/ocs/v2.php/apps/text/workspace?path=%2FShare%2FHomework
~~~

**Comment by XueSheng-GIT** [comment] 2021-02-08 15:28
Line-breaks of empty lines are still removed on Nextcloud 21 RC1. Any reason why these are removed? Is this done by intention?

**Comment by claell** [comment] 2021-03-13 11:34
Duplicate of #593

**Closed by claell** 2021-03-13 11:34 UTC
Labels: bug
