### ISSUE TITLE
Improve outline scroll to headline

### ISSUE THREAD

**Issue by provokateurin** [nextcloud/text#4460] opened 2023-07-08 08:30 UTC
**Is your feature request related to a problem? Please describe.**
When I click on a headline in the outline it scrolls to the headline correctly, but the position is weird.
If you previously were above the headline, the headline is positioned at the bottom.
If you previously were below the headline, the headline is positioned at the top (and even hidden because of the toolbar).

**Describe the solution you'd like**
The headline should be positioned in the center of the editor when scrolling to it.

**Describe alternatives you've considered**
Could also always be positioned at the top, but then it shouldn't be hidden by the toolbar.

**Comment by mejo-** [comment] 2023-11-01 14:52
Dear @provokateurin, could you provide a screencast of the issue? I'm unable to reproduce it. When clicking a heading in the outline, the heading in question is always scrolled to the the top of the editor in my tests.

Do you encounter this issues in Text documents loaded from the Files app? Or in Collectives or some other app that uses Text?

**Comment by provokateurin** [comment] 2023-11-01 15:22
Hi, I'll try to do a screencast soon. As far as I remember it was in Collectives. The scrolling part works fine, just the position of the header could be improved in my opinion. It could be that this is fixed already since I opened the issue a few months ago. I'll check and let you know.

**Comment by mejo-** [comment] 2024-09-11 10:48
Let's close this for now. @provokateurin don't hesitate to reopen and provide a screencast if you still experience the issue.

**Closed by mejo-** 2024-09-11 10:48 UTC
Labels: enhancement, needs info
