### ISSUE TITLE
problems with .sh files

### ISSUE THREAD

**Issue by szaimen** [nextcloud/text#697] opened 2020-03-06 17:06 UTC
**Describe the bug**
I cannot edit or show .sh files when I am logged in.

**To Reproduce**
1. logg into the Nextcloud
2. create a test.sh file and click on it to open/edit the file
3. the text app opens but just loads forever

**Expected behavior**
It should open the file so that I can read/edit it.

**Good to know**
Strangely enough I can view/edit that file when I share it directly over a public link. Then it gets shown correctly and loads the content.

**Client details:**
 - OS: tested on windows 10 and Android 10
 - Browser: tested on a chromium 80 based browser and firefox 73 on 

**Text app version:** (see Nextcloud apps page)
1.0.2
**Operating system:**
ubuntu 18.04 LTS
**Web server:**
apache2
**Database:**
postgresql
**PHP version:**
7.2
**Nextcloud version:** (see Nextcloud admin page)
18.0.1

**Additional information:**
I found this error while opening the file in the browser console:
![image](https://user-images.githubusercontent.com/42591237/76105381-2617fb00-5fd5-11ea-8642-11607d664893.png)

**Comment by tavinus** [comment] 2020-03-10 13:25
I have the same problem on a file with the `php` extension, loads forever.
If I duplicate the file and rename it to `.txt` > it works, renaming to `.html` > also works
Pretty weird.

**Comment by wiswedel** [comment] 2020-04-02 07:08
duplicate of #651

**Closed by wiswedel** 2020-04-02 07:08 UTC
Labels: bug
