### ISSUE TITLE
Make folder README box fixed size

### ISSUE THREAD

**Issue by TAXSET** [nextcloud/text#3511] opened 2022-12-03 12:31 UTC
## Brief

In my opinion, the folder README feature is currently implemented in a pretty annoying way. On paper it's really useful, but as it is right now it often leads to miss-clicks and overall bad UX when navigating directories with it. Here's an example:

## The issue

![Before-Loading](https://user-images.githubusercontent.com/40140669/205440357-48eaa708-7d31-47a5-8b33-656496ec7f73.png)
This is what a folder with a README looks like while the README is still being loaded.

![Before-Loaded](https://user-images.githubusercontent.com/40140669/205440393-a7d948af-cfcd-4bbf-a352-f9fdcb6f637f.png)
And this is what the folder looks like when the content is finally displayed.

The issue here is that the folders contents (files and directories) are significantly shifted down. As I (and I'm sure many others) navigate through my files pretty quickly, this often leads to me opening something I didn't intend to because the content I originally wanted to open suddenly shifted down.

## Fix proposal
Set the README box to a fixed height at all times, both while loading and displaying content. Only expand it to fit it's content if the user purposefully clicks on it.

**Comment by juliushaertl** [comment] 2022-12-05 11:36
Thanks for reporting. I'll close this as a duplicate of https://github.com/nextcloud/text/issues/2803 which covers the same matter.

**Closed by juliushaertl** 2022-12-05 11:36 UTC
Labels: enhancement, 0. Needs triage
