### ISSUE TITLE
When showing public read-only shared folder, «text» still «spamming» server with lot of push

### ISSUE THREAD

**Issue by belonesox** [nextcloud/text#5002] opened 2023-11-16 17:23 UTC
When showing public read-only shared folder, «text» still «spamming» server with lot of (rejected) pushs
![image](https://github.com/nextcloud/text/assets/1609739/e3f8d800-af72-402e-bb72-02c002a621fd)

That leeds to unwanted workload for server, browser, and lot of «red false positive» in console, that impede debugging of other issues.

May be somehow disable «all editing functions» when opened public read-only link?

**To Reproduce**

* Create «readme.md» on a folder
* Make «public share» for it
* Open shared link privately
* Look at Debugging Console

**Comment by joshtrichards** [comment] 2024-01-20 21:32
Duplicate of #5223

**Closed by joshtrichards** 2024-01-20 21:32 UTC
Labels: bug
