### ISSUE TITLE
a11y: Don't auto fill the image legend with the filename when inserting an image

### ISSUE THREAD

**Issue by raphj** [nextcloud/text#6016] opened 2024-07-08 15:56 UTC
**Describe the bug**

When inserting an image, the image legend (which is converted into the img alt attribute in HTML) is automatically filled with the filename.

This is likely harmful / not accessibility-friendly because people will inevitably leave it like this, and this is the only thing a blind user will see: a filename.

See also https://www.w3.org/TR/ATAG20/#gl_b23.

The legend should be empty by default, and a placeholder should encourage the user to type a small and concise description of the image.

It is also not clear that this is the alt text when discovering the UI. Someone not quite familiar with markdown could assume that this some text that will be displayed under the image. This should probably be made clearer. 

**To Reproduce**
1. Create a new text (.md) file
2. insert an image

**Expected behavior**

The legend is empty. The UI encourages the user to type a concise description of the image to be shown when the image cannot be loaded.

**Screenshots**

![image](https://github.com/nextcloud/text/assets/3817365/d6e95a9e-7e01-4180-8273-f2755c12ca56)

**Server details:**
- Nextcloud version: 29.0.3
- PHP Version: 8.3
- Database: MariaDB

**Client details:**
 - OS: openSUSE Tumbleweed
 - Browser: Firefox
 - Browser version: 127.0
 - Device: desktop

**Comment by provokateurin** [comment] 2024-09-04 15:04
Duplicate of https://github.com/nextcloud/text/issues/4665 @mejo-

**Closed as completed** 2024-09-04 15:06 UTC
Labels: bug
