### ISSUE TITLE
Insert and see Images over Public Link

### ISSUE THREAD

**Issue by szaimen** [nextcloud/text#198] opened 2019-07-24 08:54 UTC
**Is your feature request related to a problem? Please describe.**
Please allow us to insert and see images from access over public link.

**Describe the solution you'd like**
We should be able to view embedded pictures from public link. And also insert them. (from Nextcloud_files is enough from the beginning)

**Describe alternatives you've considered**
Also upload from local storage and other links would be very convenient.

**Additional context**
I shared a folder over a public link. Inside this folder is a .md-file, where I inserted a picture, that is also located inside the shared folder. People that acces this folder over the public link should be able to see that picture inside the .md-file, because it is also shared with them. Also they lack the ability to use the "insert picture"-button when editing the .md-file.

**Comment by juliushaertl** [comment] 2019-07-24 11:25
Thanks for reporting. This is actually a duplicate of https://github.com/nextcloud/text/issues/54

**Closed by juliushaertl** 2019-07-24 11:25 UTC
Labels: enhancement
