### ISSUE TITLE
Todo List Checkboxes

### ISSUE THREAD

**Issue by sunjam** [nextcloud/text#110] opened 2019-06-27 14:35 UTC
![1561646005](https://user-images.githubusercontent.com/1787238/60274972-ef1e1100-98ad-11e9-93e6-eed93517615d.png)

**Is your feature request related to a problem? Please describe.**
Todo lists are supported in tiptap [as described here on their website](https://tiptap.scrumpy.io/todo-list).

**Describe the solution you'd like**
Todo checkboxes are an important inclusion for the Text app, as a Markdown shortcut, and as part of the WYSIWYG editor menu.  Thanks!

**Comment by jancborchardt** [comment] 2019-06-27 16:13
@juliushaertl is this a duplicate of #93? :)

**Comment by juliushaertl** [comment] 2019-07-01 08:29
@jancborchardt Yes. Let's close this in favor of #93

**Closed by juliushaertl** 2019-07-01 08:29 UTC
Labels: enhancement, feature: formatting
