### ISSUE TITLE
PDF Export

### ISSUE THREAD

**Issue by aiveras** [nextcloud/text#378] opened 2019-10-24 11:58 UTC
The editor is great, but it lacks the possibility to export written documents quickly as pdf and send them. 
An export button on the right would make life much easier for many. Currently you have to convert the whole text with other tools...

**Comment by juliushaertl** [comment] 2019-10-24 12:09
duplicate of https://github.com/nextcloud/text/issues/112

**Closed by juliushaertl** 2019-10-24 12:09 UTC
Labels: enhancement
