### ISSUE TITLE
Share links are not going to the clipboard when copied from the Sharing sidebar from within the md document

### ISSUE THREAD

**Issue by absort0** [nextcloud/text#4191] opened 2023-05-15 10:48 UTC
**Describe the bug**
Copying internal or external share links from the share sidebar from withing the editing view of a md file doesn't work, the link is not added to the clipboard. Quitting the editor and copying the share links from the folder view works as expected.

**To Reproduce**
1. Open a .md file for editing
2. Click on the three-dots menu and select *Open sidebar*
3. Switch to the *Sharing* tab
4. Click on the *Copy to clipboard* icon to copy the internal link to the clipboard
5. Paste the link, **it should not be the link you expected to have copied**

**Expected behavior**
Copying internal or external share links from the sharing tab to the clipboard should actually insert the links in the clipboard.

**Client details:**
 - OS: Debian Linux 11.7
 - Browser: Chromium, Firefox
 - Version: 113.0.5672.63,  113.0.1
 - Device: ThinkPad T480
 
<details>
<summary>Server details</summary>

**Text app version:** 3.6.1
**Operating system:** Debian Linux 11.7
**Web server:** Nginx
**Database:** Mysql
**PHP version:** 7.4.33

**Nextcloud version:** 25.0.3 

</details>

<details>

**Comment by juliushaertl** [comment] 2023-05-15 12:25
Please make sure to run the most recent version of Nextcloud. This has been fixed some time ago already. Closing as a duplicate of https://github.com/nextcloud/server/issues/36606

**Closed by juliushaertl** 2023-05-15 12:25 UTC
Labels: bug
