### ISSUE TITLE
Can't open text files in shared folders with hidden download button

### ISSUE THREAD

**Issue by rob1998** [nextcloud/text#1547] opened 2021-04-08 18:03 UTC
### Steps to reproduce
**To Reproduce**
1. Create a new folder
2. Create a text file inside the folder (.md or .txt doesn't matter)
3. Create a new Share link
4. Select the hide download button
5. Open the link in an incognito window or other browser
6. Try to open the file

To make it weirder:
a. If you skip step 4, it works but only until you refresh the page. After that the bug also occurs
b. If you disable the "hide download" option after step 6, it still doesn't work but it does give me the option to click the edit button, which uses https://nextcloud-url/apps/text/public/session/create
c. even after removing the share link and creating a new one it does not seem to work for this folder

### Expected behaviour
A preview of the file appears

### Actual behaviour
Content of file is not loaded

## Server configuration detail

**Operating system:** Linux 5.10.19-Unraid #1 SMP Sat Feb 27 08:00:30 PST 2021 x86_64

**Webserver:** nginx/1.18.0 (fpm-fcgi)

**Database:** mysql 10.4.18

**PHP version:** 

7.4.15
Modules loaded: Core, date, libxml, pcre, zlib, filter, hash, readline, Reflection, SPL, session, cgi-fcgi, bcmath, bz2, ctype, curl, dom, fileinfo, ftp, gd, gmp, iconv, standard, intl, json, ldap, mbstring, openssl, pcntl, PDO, pgsql, posix, imap, SimpleXML, smbclient, sodium, sqlite3, xml, xmlwriter, zip, exif, mysqlnd, pdo_pgsql, pdo_sqlite, Phar, xmlreader, pdo_mysql, apcu, igbinary, redis, memcached, imagick, mcrypt, libsmbclient, Zend OPcache

**Nextcloud version:** 21.0.0 - 21.0.0.18

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** Docker

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.7.0
 - activity: 2.14.3
 - admin_audit: 1.11.0
 - apporder: 0.12.0
 - calendar: 2.2.0
 - camerarawpreviews: 0.7.10
 - cloud_federation_api: 1.4.0
 - comments: 1.11.0
 - contacts: 3.5.1
 - contactsinteraction: 1.2.0
 - dashboard: 7.1.0
 - data_request: 1.8.0
 - dav: 1.17.1
 - deck: 1.3.1
 - documentserver_community: 0.1.9
 - encryption: 2.9.0
 - external: 3.8.1
 - extract: 1.3.1
 - federatedfilesharing: 1.11.0
 - federation: 1.11.0
 - files: 1.16.0
 - files_3d: 0.3.3
 - files_accesscontrol: 1.11.0
 - files_linkeditor: 1.1.5
 - files_markdown: 2.3.3
 - files_pdfviewer: 2.1.0
 - files_rightclick: 1.0.0
 - files_sharing: 1.13.1
 - files_trashbin: 1.11.0
 - files_versions: 1.14.0
 - files_videoplayer: 1.10.0
 - groupfolders: 9.0.0
 - guests: 1.6.2
 - impersonate: 1.8.0
 - integration_google: 1.0.0
 - integration_reddit: 0.0.11
 - issuetemplate: 0.7.0
 - logreader: 2.6.0
 - lookup_server_connector: 1.9.0
 - metadata: 0.13.0
 - nextcloud_announcements: 1.10.0
 - notes: 4.0.4
 - notifications: 2.9.0
 - oauth2: 1.9.0
 - password_policy: 1.11.0
 - passwords: 2021.4.0
 - photos: 1.3.0
 - privacy: 1.5.0
 - provisioning_api: 1.11.0
 - quota_warning: 1.10.0
 - rainloop: 7.1.2
 - ransomware_protection: 1.10.0
 - recommendations: 1.0.0
 - registration: 1.1.1
 - richdocuments: 4.0.4
 - serverinfo: 1.11.0
 - settings: 1.3.0
 - sharebymail: 1.11.0
 - social: 0.4.2
 - sociallogin: 4.4.0
 - support: 1.4.0
 - survey_client: 1.9.0
 - suspicious_login: 4.0.0
 - systemtags: 1.11.0
 - text: 3.2.0
 - theming: 1.12.0
 - twofactor_backupcodes: 1.10.0
 - twofactor_totp: 6.0.0
 - updatenotification: 1.11.0
 - user_ldap: 1.11.0
 - user_status: 1.1.1
 - viewer: 1.5.0
 - weather_status: 1.1.0
 - workflowengine: 2.3.0
Disabled:
 - files_external
 - firstrunwizard

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```

```
</details>

**Are you using external storage, if yes which one:** 

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** 

<details><summary>LDAP configuration (delete this par if not used)</summary>

```

```
</details>

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36

**Operating system:** Windows

## Logs

<details><summary>Web server error log</summary>

```

```
</details>

<details><summary>Nextcloud log</summary>

```

```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
            Failed to load resource: the server responded with a status of 401 () apps/text/session/create:1
        b) The network log
            https://nextcloud-url/apps/text/session/create returns a 401 error (message: "Current user is not logged in")
	c) ...
</details>

**Comment by marcelklehr** [comment] 2022-10-18 10:55
Hi! I cannot reproduce this with the latest versions. Please shout if this is still an issue. Otherwise l'll close this for now.

**Closed by marcelklehr** 2022-10-18 10:55 UTC
Labels: bug, needs triage: marcel
