### ISSUE TITLE
Tab-indent of lists is broken in viewer

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/text#4217] opened 2023-05-22 14:53 UTC
Indenting list items is currently broken in the viewer (works in rich workspace though). 

Could be related to the focus trap handling introduced with 26, possibly backported to 25, so far only tested to be an issue on 27.

**Comment by mejo-** [comment] 2023-06-06 13:14
I think this is a duplicate of #3493, no?

**Closed by mejo-** 2023-06-06 13:14 UTC
Labels: bug
