### ISSUE TITLE
Hemingway App-like integration

### ISSUE THREAD

**Issue by monsieurhannes** [nextcloud/text#647] opened 2020-02-02 22:24 UTC
Hej,

first of all I love the app!
I was wondering if there could be an implementation of a proofreader, like the [Hemingway App](http://www.hemingwayapp.com/).
Hemingway is not open source from what I could see, but there are some similar libraries that do the job. I could find this article: https://dev.to/samwsoftware/creating-my-own-hemingway-app-143
and this apparently dead github-repo: https://github.com/kdzwinel/Proofreader (or it's perfect?)
Anyway, I think this would be a great feature that would distinguish the text app even more from other apps out there. I don't know any service apart from hemingwayapp.com that has such a proof reader.
Thanks for your efforts with the app, really beautiful!

**Comment by brainchild0** [comment] 2020-06-17 05:10
Related to, and possibly duplicate of, #3.

**Comment by jancborchardt** [comment] 2020-07-07 15:47
Closing as duplicate of #3, @monsieurhannes good find with the repository, added it as a comment at https://github.com/nextcloud/text/issues/647

**Closed by jancborchardt** 2020-07-07 15:47 UTC
