### ISSUE TITLE
Endless loading for all files except .txt and .md

### ISSUE THREAD

**Issue by Pilzinsel64** [nextcloud/text#745] opened 2020-04-02 06:48 UTC
### Steps to reproduce
1. Open the files app in a browser
2. Navigate to a directory that is your own.
3. In the files app just create a new file called "test.json".
4. If the text editor does not open automatically, click on the files.

### Expected behaviour
Until v18.0.0 It was possible to click a file (or while creating a new one) and then the text editor showed up. After one or two seconds I was able to see and edit the content.

### Actual behaviour
When I click on a file, like .php, .json, .xml, the text editor does open but keep loading without showing the content.

In Settings->Protocoll there is no error or any log.

I have three nextcloud instances on very different servers. On every instance I get the same problem. With different Windows clients and different browsers. This bug does not happen in the Android-App btw, only in the browser.

This issues seems to be same as #651 but I want open a seperate one to post everything you need seperatly.

### Screenshots
![grafik](https://user-images.githubusercontent.com/23138465/78215808-b5bba700-74b8-11ea-9afb-836a56803aff.png)
Client device and OS specification:
![grafik](https://user-images.githubusercontent.com/23138465/78216709-bead7800-74ba-11ea-8308-e53e128a6d1a.png)

## Server configuration detail

**Operating system:** SunOS localhost 5.10 Generic_150401-49 i86pc SunOS localhost 5.10 Generic_150401-49 i86pc SunOS localhost 5.10 Generic_150401-49 i86pc SunOS localhost 5.10 Generic_150401-49 i86pc

**Webserver:** Apache/2.4.41 (Unix) (cgi-fcgi) (on Strao Webspace)

**Database:** mysql 5.6.42 (on Strao Webspace) | 5.7.24 (nextcloud 18 snap on ubuntu)

**PHP version:** 7.3

7.3.16
Modules loaded: Core, date, ereg, libxml, openssl, pcre, sqlite3, zlib, bcmath, bz2, calendar, ctype, curl, dba, dom, hash, fileinfo, filter, ftp, gd, gettext, SPL, iconv, session, intl, json, lzf, mailparse, mbstring, mcrypt, mysql, mysqli, pcntl, standard, PDO, pdo_mysql, pdo_sqlite, Phar, posix, Reflection, imap, SimpleXML, soap, sockets, exif, tidy, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, cgi-fcgi, Zend OPcache

**Nextcloud version:** 18.0.3 - 18.0.3.0

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - admin_audit: 1.8.0
 - apporder: 0.9.0
 - bruteforcesettings: 1.5.0
 - calendar: 2.0.2
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - contacts: 3.2.0
 - dav: 1.14.0
 - dropit: 0.4.0
 - external: 3.5.0
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_external: 1.9.0
 - files_external_onedrive: 1.0.7
 - files_pdfviewer: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - forms: 1.1.1
 - groupfolders: 6.0.3
 - guests: 1.4.3
 - issuetemplate: 0.6.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - nextcloud_announcements: 1.7.0
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - occweb: 0.0.7
 - ocdownloader: 1.7.6
 - password_policy: 1.8.0
 - photos: 1.0.0
 - polls: 1.3.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - spreed: 8.0.6
 - support: 1.1.0
 - survey_client: 1.6.0
 - systemtags: 1.8.0
 - talk_simple_poll: 1.1.0
 - tasks: 0.12.1
 - text: 2.0.0
 - theming: 1.9.0
 - theming_customcss: 1.5.0
 - twofactor_admin: 2.0.0
 - twofactor_backupcodes: 1.7.0
 - twofactor_email: 1.0.1
 - twofactor_nextcloud_notification: 2.2.0
 - twofactor_totp: 4.1.3
 - updatenotification: 1.8.0
 - viewer: 1.2.0
 - workflowengine: 2.0.0
Disabled:
 - encryption
 - recommendations
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "maintenance": false,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "pilzinsel64.com",
        "www.pilzinsel64.com",
        "localhost"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "tempdirectory": "\/mnt\/web418\/a2\/84\/510199884\/htdocs\/www\/pilzinsel64.com\/pilzcloud\/data\/tmp",
    "dbtype": "mysql",
    "version": "18.0.3.0",
    "overwrite.cli.url": "https:\/\/pilzinsel64.com\/pilzcloud",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "mail_smtpmode": "smtp",
    "mail_sendmailmode": "smtp",
    "mail_smtpsecure": "ssl",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "app_install_overwrite": [
        "occweb",
        "dropit",
        "files_external_onedrive",
        "ocdownloader"
    ],
    "theme": "",
    "loglevel": 2,
    "twofactor_enforced": "true",
    "twofactor_enforced_groups": [],
    "twofactor_enforced_excluded_groups": []
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0

**Operating system:** Windows 10 v1903

## Logs

<details><summary>Web server error log</summary>

```
Have no acces to it on the Strato Webspace.
If you need the logs of my other two instancs, just tell me.
```
</details>

<details><summary>Nextcloud log</summary>

```
Strato Webspace:
[nextcloud.zip](https://github.com/nextcloud/text/files/4419248/nextcloud.zip)
If you need the logs of my other two instancs, just tell me.
```
</details>

**Comment by wiswedel** [comment] 2020-04-02 07:08
duplicate of #651

**Closed by wiswedel** 2020-04-02 07:08 UTC
Labels: bug

**Comment by cyayon** [comment] 2020-05-03 18:39
Hi,

when this app is enabled, i have an infinite loading icon on the front of file app (default page after logon). 
No particular error in logs.
This issue happen, since upgrade from 17.0.4 to 18.0.4.
I have to disable file app to remove this loading icon on file app.

thx.
