### ISSUE TITLE
Editing Link text from Smart Picker - Link removed if https deleted

### ISSUE THREAD

**Issue by isaw1** [nextcloud/text#4479] opened 2023-07-11 08:37 UTC
Unable to fully edit link text in a 'Auto Picker link'
Only portions of the URL text can be edited

Issues 
a) If you highlight text, and use link picker to select a file the text is replaced with the https://url.to/file/1  
Desired behaviour:  the highlighted text should remain, 

b) if you insert a link via smart picker, and then try to edit the text, the link will be removed if the https:// text is changed in any way.
Desired behaviour:  the link text should be editible to any characters

**To Reproduce**
1. type text,
2. highlight and click create link
3. select a file from smart picker
4. try to remove any part of https:// text    link will disapear

**Expected behavior**

a) If text is highlighted it should retain the text
b) all of the address should be editable,

There is not ability from the link menu to edit text,
there is no ability to view or edit standard markdown for links  eg  [Link Text goes here] (.https//url.to/goes/here)

**Server details:**
- Nextcloud version: 27.0.0
- Server OS: Unraid/AIO

**Client details:**
 - Server OS: Unraid/AIO
 - Browser: Chrome on win11
 - Browser version:  114.0.5735.199
 - Device: desktop

**Comment by elzody** [comment] 2024-09-17 09:55
Closing this for now as I am unable to reproduce the issue.
Version 27 of Nextcloud is now considered end of life, and the issue does not seem to be present on version 28+.

**Closed by elzody** 2024-09-17 09:55 UTC
Labels: bug
