### ISSUE TITLE
Show Table of Content (TOC) as default or save state

### ISSUE THREAD

**Issue by lars-becker** [nextcloud/text#3692] opened 2023-01-22 01:46 UTC
**Is your feature request related to a problem? Please describe.**
The new TOC in Text/Collectives is really useful, but it's quite cumbersome to use and the menu isn't self-explaining:

1. It's cumbersome to use because on long texts the user has to navigate to a button thats hidden on the second level of a menu. 2 clicks are needed for every newly loaded page. 
2. It's semantical confusing because most buttons are for editing. So the "h1" suggests there are buttons to set the headers; not that display options can be found there.

**Describe the solution you'd like**

The TOC should be shown in the viewer by default if texts have more than lets say 2 headers oder a length of xxx characters or even better: the state should be saved as default for the next displayed pages. This would allow for much faster navigation in text documents and leads to faster information retrieval which the purpose of a wiki.

**Describe alternatives you've considered**
The alternative is to do two clicks every time a longer document is displayed.

**Comment by max-nextcloud** [comment] 2023-02-01 09:49
I think this is a duplicate of #3586 - feel free to reopen if you disagree.

**Closed by max-nextcloud** 2023-02-01 09:49 UTC
Labels: enhancement

**Comment by lars-becker** [comment] 2023-02-02 14:40
Sorry, didn't saw it. It's the same issue indeed.
