### ISSUE TITLE
Toolbar has black background and black icons

### ISSUE THREAD

**Issue by AuspeXeu** [nextcloud/text#2374] opened 2022-05-09 07:26 UTC
![image](https://user-images.githubusercontent.com/2115696/167360794-1fb55e74-a2f6-46bd-9864-6134913153f3.png)

Nextcloud: 24.0.0
Text: 3.5.1

**Comment by juliushaertl** [comment] 2022-05-09 09:30
I cannot reproduce that on 24.0.0. Could you tell if you have any special accessibility settings enabled in your accounts personal settings?

**Comment by AuspeXeu** [comment] 2022-05-09 10:51
What is a bit strange as well, is that the settings page tells me I am on 24.0.0 (docker) but I don't have the extended sharing settings announced in the blog post for 24.0.0. Any clue why that is? Maybe this is correlated?

**Comment by juliushaertl** [comment] 2022-05-09 10:56
Which docker image is it that you are using there? It looks a bit like a regression that might be re related to the current development branch for the next 24 release, so it could be happening if you run a daily snapshot of that.

**Comment by AuspeXeu** [comment] 2022-05-09 11:52
I am using the `nextcloud:24` tag

**Comment by szaimen** [comment] 2022-05-09 13:27
can you try clearing your browser cache? I think this should be fixed with NC24...

**Comment by juliushaertl** [comment] 2022-05-09 15:14
Looks like this is not applying the styles from https://github.com/nextcloud/viewer/blob/master/src/views/Viewer.vue#L840-L852 anymore which is a regression on master but I would not expect that on 24

**Comment by AuspeXeu** [comment] 2022-05-09 15:23
@szaimen persists even after I clear the cache unfortunately

**Comment by juliushaertl** [comment] 2022-05-13 14:11
I also cannot reproduce using the latest docker: `docker run -d -p 8091:80 nextcloud:24`

```
nextcloud                                          24                                              70077b5f562d   14 hours ago    829MB
```

Can you tell which exact hash your docker image has?

**Comment by AuspeXeu** [comment] 2022-05-13 14:35
Not sure how to tell you this hash. Does this help?

![image](https://user-images.githubusercontent.com/2115696/168306721-cdd42173-2dc1-4e0c-8c5f-64919c075175.png)

**Comment by juliushaertl** [comment] 2022-05-13 15:01
OK, same hash here so no clue on what could cause that other than an outdated browser cache :/

**Comment by AuspeXeu** [comment] 2022-05-13 15:58
Is there a chance that another app interfers?

**Comment by juliushaertl** [comment] 2022-05-13 18:01
Yeah could be worth to try disabling them one by one to see if there is any difference. The actual close button is coming from the viewer app so one additional thing to check would be if that also happens on images.

**Comment by AuspeXeu** [comment] 2022-05-16 06:45
This is what I see during an image preview

![image](https://user-images.githubusercontent.com/2115696/168534523-624735b2-8929-4e53-84eb-ccc03cac3c3f.png)

**Comment by amenolo** [comment] 2022-06-16 14:52
According to my tests the bug depends on _accessibility app_ being disabled, at least.

Debian 11
Apache 2.4
PHP 8.0
NC 24.0.1 new installation with standard app enabled and updated

**Comment by avbor** [comment] 2022-06-16 15:10
Yea, when i enable Accessibility App, toolbar looks like:
![image](https://user-images.githubusercontent.com/32452033/174101365-e691b566-07e8-4794-aafc-5543c21af00f.png)
But, it helps because it changes the background of the toolbar to light.
The question of why the buttons remain dark on a dark background is open.

**Comment by amenolo** [comment] 2022-06-16 15:26
Yep, with _bug_ I was in the first place referring to the toolbar background color turning dark, btw enabling the dark theme (never tried before), buttons turn properly white.

**Comment by danxuliu** [comment] 2022-06-16 16:54
This is a regression introduced in https://github.com/nextcloud/viewer/pull/1202 @juliushaertl

[The colour of the buttons in the modal header is set to white](https://github.com/nextcloud/nextcloud-vue/blob/122f3716760431b7d8ce499d8254e3777b2c20ee/src/components/Modal/Modal.vue#L713-L716), but now the colour of the SVG element inside the button is always overriden with the color of the text, thus causing the button to become (almost) black.

Note that the accessibility app needs to be disabled, otherwise the bug can not be reproduced.

**Closed** 2022-07-07 07:08 UTC
Labels: bug, needs info
