### ISSUE TITLE
Options to weather edit md text (source) or edit as a preview md file

### ISSUE THREAD

**Issue by brunoschroeder** [nextcloud/text#939] opened 2020-07-21 15:27 UTC
I am a terminal/vim user who loves syntax highlighting my md files, but I am NOT worried how they will eventually be previewed, as far as the files text (source) are kept the way I left them, last time I saw them in vim.

**Issue/Bug:**
When opening an md file on my iOs next cloud app, the file is processed and a lot of it is changed. Its text suffers many changes without any user confirmation!
(annoying example - lines that dont end with many spaces are transformed into one single line, because markdown interprets it as a long line when it is not the intention)

**Needed Feature:**
Please allow the iOs App user edit an md file as pure text or as a processed note - this is the beauty of markdown, and this is why we fled from html, latex or all wierd formats and went for markdown in the first place.

**My current ridiculous workaround:**
All .md files are .md.txt files, and my vim knows .md.txt should have markdown syntax highlight.
By the way this is the shenanigans I have to do with yaml files.
I hope I am helping nextcloud experience to get better. Would love to help you guys with all I can!

**Comment by DanScharon** [comment] 2020-08-05 15:25
yes, this would help our users tremendously who miss the old markdown editor app. [CodiMD](https://github.com/codimd/server) shows how this can be done.

**Comment by juliushaertl** [comment] 2020-08-18 19:57
Duplicate of #439 and #123, see https://github.com/nextcloud/text/issues/123#issuecomment-508723049 for some details on why this is a technical limitation. In general this the primary focus of the text app is rich text editing.

**Closed by juliushaertl** 2020-08-18 19:57 UTC
Labels: enhancement

**Comment by DanScharon** [comment] 2020-08-19 14:59
@juliushaertl I understand the primary focus of the text app. But most of us are looking for a way to offer both methods to our users, richt text editing and the markdown editor app.
In an ideal scenario I would have the `text` app as the default and install `files_markdown` app in addition to that, which could then be started optionally via the context menu ("Edit with Markdown editor"). But `files_markdown` depends on the old `files_texteditor` which in turn conflicts with `text`. And so the cat bites its own tail :-\

**Comment by juliushaertl** [comment] 2020-08-19 20:59
Yes, I see the point there. This is also why we released https://apps.nextcloud.com/apps/files_texteditor to the app store for Nextcloud 18+ and it should stil work fine with files_markdown even if text is enabled.

**Comment by brunoschroeder** [comment] 2020-08-20 10:47
Please do NOT close this.

This used to work! We used to be able to edit our markdowns as text.

It is NOT okay to change markdown sources when rendering it/changing it without any user conset.

The user uploads a file to NextCloud, tries to edit it, and destroys his/her work. This is not a good experience, at least a warning sign telling the user to keep his file/backup it otherwise NextCloud will completely alter it.

**Comment by DanScharon** [comment] 2020-08-20 15:57
> Yes, I see the point there. This is also why we released https://apps.nextcloud.com/apps/files_texteditor to the app store for Nextcloud 18+ and it should stil work fine with files_markdown even if text is enabled.

wow, great! I can confirm that this works and doesn't conflict with `text`anymore!
