### ISSUE TITLE
Too much space between lines in editor under iOS

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/text#1708] opened 2021-07-07 15:18 UTC
Under iOS - and with iPhone 12 : 

![Simulator Screen Shot - iPhone 12 - 2021-07-07 at 16 58 13](https://user-images.githubusercontent.com/8616947/124785084-d6d63780-df46-11eb-86e3-b64faf2cf06e.png)

1 - the first letter and the "..." menu are overlap
2 - every new line is double or the interline is 2x

For other question I am always available.

**Comment by szaimen** [comment] 2021-07-09 14:28
1. is fixed in https://github.com/nextcloud/text/pull/1710

**Comment by max-nextcloud** [comment] 2022-11-14 08:27
Changed the issue description to refer to the remaining part of the issue.

**Comment by max-nextcloud** [comment] 2022-11-14 08:31
I think #2775 will fix this. What's happening here is that enter was always understood to mean start a new paragraph. Having a bit of spacing between paragraphs is to be expected. `shift+enter` would create a hard line break without a new para. However there was no way to create this on mobile.

The PR makes it so that one time pressing enter will create a hard line break - with a normal distance between the lines. Pressing enter twice will create a new paragraph. This behavior will only change on mobile.

**Comment by juliushaertl** [comment] 2022-11-14 08:43
Yes, with the current implementation this is expected behavior, so lets close this as a duplicate of https://github.com/nextcloud/text/issues/2761

**Closed by juliushaertl** 2022-11-14 08:43 UTC
Labels: bug, feature: formatting, 2. developing, mobile, client: 🤖🍏 mobile
