### ISSUE TITLE
Links containing underscore do not work

### ISSUE THREAD

**Issue by 42ske** [nextcloud/text#2379] opened 2022-05-10 07:07 UTC
**Describe the bug**
If an md-File ends with a link containing an underscore the link is not working anymore if you open the file the next time. "_“ is replaced by "\_".

If you have a link-Text without _ the link still works, e.g. „Link" contains https://docs.nextcloud.com/server/stable/user_manual/de/files/projects.html

**To Reproduce**
1. Open a md-file.
2. Add a link containing an underscore as last text within the file (no further letters following) e. g. https://docs.nextcloud.com/server/stable/user_manual/de/files/projects.html
3. close the file (or finish the file within Collectives)
4. reopen the file an click on the link

**Expected behavior**
No changes should be done in Link-Texts so that they just work.

**Client details:**
 - OS: macOS 12.3.1
 - Browser: Firefox 100.0

Are the following infos necessary in this case?

Thanks for having a look.

<details>
<summary>Server details</summary>

**Text app version:** (see Nextcloud apps page)

**Operating system:**

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by mejo-** [comment] 2022-05-10 07:56
Thanks for your report! Which Nextcloud version do you use?

I was able to reproduce this on Nextcloud 23, but not on Nextcloud 24.

We recently updated the markdown input/paste rules in Nextcloud 22 and 23: https://github.com/nextcloud/text/pull/1964
This seems to be fixed with the migration to Tiptap v2.

**Comment by juliushaertl** [comment] 2022-05-13 14:04
Lets close this then.

**Comment by mejo-** [comment] 2022-06-23 11:55
Indeed, verified that it's closed.

**Closed by mejo-** 2022-06-23 11:55 UTC
Labels: bug, 1. to develop, format: markdown

**Comment by jancborchardt** [comment] 2022-08-22 22:33
@mejo- I just ran into this with the version we have deployed on our instance – seems the problem is back or still there?
Example link e.g. https://www.bitvtest.de/bitv_test/das_testverfahren_im_detail/verfahren.html
![image](https://user-images.githubusercontent.com/925062/186030337-c9cb8410-f99e-4d8b-8190-aeaacb316853.png)

**Comment by jancborchardt** [comment] 2022-08-22 22:34
Ah nevermind – that was actually a link pasted before the fix, and I guess that would be difficult to distinguish? Newly pasted links work well. :)
