### ISSUE TITLE
[PHP] Error: fseek(): stream does not support seeking at ... (with External Storage WebDAV)

### ISSUE THREAD

**Issue by cju77** [nextcloud/text#550] opened 2020-01-12 12:49 UTC
File gets locked on editing text file (*.txt). Uploading/Sync to external storage isn't possible anymore.

**To Reproduce**
1. Add an external storage (WebDAV)
2. Add an text file with suffix .txt
3. Edit the text many times with text app

**Text app version:** 1.1.1

**Operating system:**

**Web server:** Apache

**Database:** MySQL 5.7.24

**PHP version:** 7.3.13

**Nextcloud version:** 17.0.2

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
[PHP] Error: fseek(): stream does not support seeking at /home/www/secure/apps/files_external/3rdparty/icewind/streams/src/Wrapper.php#82

GET /remote.php/files/External/dir1/example_2020_01.txt
from xxx.xxx.xxx.xxx by user1 at 2020-01-12T12:11:12+00:00
```

**Comment by juliushaertl** [comment] 2020-01-24 17:33
Do you have a full trace for that error message?

**Comment by cju77** [comment] 2020-01-24 18:00
The log entry given above is complete.

This log entry always comes before and after (i deleted some private data!):

{"reqId":"XhsLErkeIDMAAtFvikYAAAAE","level":1,"time":"2020-01-12T12:03:30+00:00","remoteAddr":"5.146.132.241","user":"...","app":"no app in context","method":"POST","url":"/index.php/apps/text/session/sync","message":{"Exception":"OCP\\Lock\\LockedException","Message":"\"files/b2d1648201a43079f91b07e4ce977d5b\" is locked","Code":0,"Trace":[{"file":"/home/www/secure/lib/private/Files/Storage/Common.php","line":807,"function":"changeLock","class":"OC\\Lock\\DBLockingProvider","type":"->","args":["files/b2d1648201a43079f91b07e4ce977d5b",2]},{"file":"/home/www/secure/lib/private/Files/Storage/Wrapper/Wrapper.php","line":615,"function":"changeLock","class":"OC\\Files\\Storage\\Common","type":"->","args":["...LoBu/Stundenerfassung/Stunden_2020_01.txt",2,{"__class__":"OC\\Lock\\DBLockingProvider"}]},{"file":"/home/www/secure/lib/private/Files/Storage/Wrapper/Wrapper.php","line":615,"function":"changeLock","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["100338/Stundenerfassung/Stunden_2020_01.txt",2,{"__class__":"OC\\Lock\\DBLockingProvider"}]},{"file":"/home/www/secure/lib/private/Files/Storage/Wrapper/Wrapper.php","line":615,"function":"changeLock","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["100338/Stundenerfassung/Stunden_2020_01.txt",2,{"__class__":"OC\\Lock\\DBLockingProvider"}]},{"file":"/home/www/secure/lib/private/Files/Storage/Wrapper/Wrapper.php","line":615,"function":"changeLock","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["100338/Stundenerfassung/Stunden_2020_01.txt",2,{"__class__":"OC\\Lock\\DBLockingProvider"}]},{"file":"/home/www/secure/lib/private/Files/Storage/Wrapper/Wrapper.php","line":615,"function":"changeLock","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["100338/Stundenerfassung/Stunden_2020_01.txt",2,{"__class__":"OC\\Lock\\DBLockingProvider"}]},{"file":"/home/www/secure/lib/private/Files/View.php","line":1981,"function":"changeLock","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["100338/Stundenerfassung/Stunden_2020_01.txt",2,{"__class__":"OC\\Lock\\DBLockingProvider"}]},{"file":"/home/www/secure/lib/private/Files/View.php","line":1149,"function":"changeLock","class":"OC\\Files\\View","type":"->","args":["/.../files/S1-E-Akten/100338/Stundenerfassung/Stunden_2020_01.txt",2]},{"file":"/home/www/secure/lib/private/Files/View.php","line":694,"function":"basicOperation","class":"OC\\Files\\View","type":"->","args":["file_put_contents","/.../files/S1-E-Akten/100338-.../LoBu/Stundenerfassung/Stunden_2020_01.txt",["update","write"],"Erfassung beendet und freigeben am: Sonntag, 12. Januar 2020, 13:03, cj\n\n--- AKTUELLE MA-LISTE ---\n\nP-...------------------------\n\n--- HINWEISE ---\n1. Bitte TAB-TASTE (Tabulator) zwischen den \"Spalten\" benutzen! KEINE LEERZEICHEN!\n2. Die Spalten \"AS\", \"LA#\" und \"T#\" sind in der Regel immer gleich. Die Werte können einfach kopiert und am Ende nach der Stundeneingabe eingefügt werden.\n3. In der ersten Zeile des Bearbeitungsabschnitts (507524 ...) bitte immer NUR Monat/Jahr anpassen!\n-----------------\n\n*\t*\t*\nP-Nr\tTag\tStd\tAS\tLA#\tT#\n\t\t\t1\t2200\t1\n\n------------------------------------\n--- Bearbeitungsabschnitt ---\n\n507524\t10004\t01/2020\n2\t4\t3,5\t1\t2200\t1\n2\t12\t8,75\t1\t2200\t1\n4\t10\t7,5\t1\t2200\t1\n4\t12\t6,5\t1\t2200\t1\n\n\n\n--- Bearbeitungsabschnitt Ende ---\n----------------------------------\n\nErläuterungen:\n\nAusfallschlüssel (AS)\t\r\n0\tfrei\r\n1\tgearbeitet\r\nK\tAU eingereicht\r\n\t\r\nLohnartnummer (LA#)\r\n2200\tAushilfe, Std\r\n2000\tGehalt"]},{"file":"/home/www/secure/lib/private/Files/Node/File.php","line":66,"function":"file_put_contents","class":"OC\\Files\\View","type":"->","args":["/.../files/S1-E-Akten/.../Stundenerfassung/Stunden_2020_01.txt","Erfassung beendet und freigeben am: Sonntag, 12. Januar 2020, 13:03, cj\n\n--- AKTUELLE MA-LISTE ---\n\nP-...n------------------------\n\n--- HINWEISE ---\n1. Bitte TAB-TASTE (Tabulator) zwischen den \"Spalten\" benutzen! KEINE LEERZEICHEN!\n2. Die Spalten \"AS\", \"LA#\" und \"T#\" sind in der Regel immer gleich. Die Werte können einfach kopiert und am Ende nach der Stundeneingabe eingefügt werden.\n3. In der ersten Zeile des Bearbeitungsabschnitts (507524 ...) bitte immer NUR Monat/Jahr anpassen!\n-----------------\n\n*\t*\t*\nP-Nr\tTag\tStd\tAS\tLA#\tT#\n\t\t\t1\t2200\t1\n\n------------------------------------\n--- Bearbeitungsabschnitt ---\n\n507524\t10004\t01/2020\n2\t4\t3,5\t1\t2200\t1\n2\t12\t8,75\t1\t2200\t1\n4\t10\t7,5\t1\t2200\t1\n4\t12\t6,5\t1\t2200\t1\n\n\n\n--- Bearbeitungsabschnitt Ende ---\n----------------------------------\n\nErläuterungen:\n\nAusfallschlüssel (AS)\t\r\n0\tfrei\r\n1\tgearbeitet\r\nK\tAU eingereicht\r\n\t\r\nLohnartnummer (LA#)\r\n2200\tAushilfe, Std\r\n2000\tGehalt"]},{"file":"/home/www/secure/apps/text/lib/Service/DocumentService.php","line":272,"function":"putContent","class":"OC\\Files\\Node\\File","type":"->","args":["Erfassung beendet und freigeben am: Sonntag, 12. Januar 2020, 13:03, cj\n\n--- AKTUELLE MA-LISTE ---\n\nP-...------------------------\n\n--- HINWEISE ---\n1. Bitte TAB-TASTE (Tabulator) zwischen den \"Spalten\" benutzen! KEINE LEERZEICHEN!\n2. Die Spalten \"AS\", \"LA#\" und \"T#\" sind in der Regel immer gleich. Die Werte können einfach kopiert und am Ende nach der Stundeneingabe eingefügt werden.\n3. In der ersten Zeile des Bearbeitungsabschnitts (507524 ...) bitte immer NUR Monat/Jahr anpassen!\n-----------------\n\n*\t*\t*\nP-Nr\tTag\tStd\tAS\tLA#\tT#\n\t\t\t1\t2200\t1\n\n------------------------------------\n--- Bearbeitungsabschnitt ---\...-- Bearbeitungsabschnitt Ende ---\n----------------------------------\n\nErläuterungen:\n\nAusfallschlüssel (AS)\t\r\n0\tfrei\r\n1\tgearbeitet\r\nK\tAU eingereicht\r\n\t\r\nLohnartnummer (LA#)\r\n2200\tAushilfe, Std\r\n2000\tGehalt"]},{"file":"/home/www/secure/apps/text/lib/Service/ApiService.php","line":166,"function":"autosave","class":"OCA\\Text\\Service\\DocumentService","type":"->","args":[2070521,572,"Erfassung beendet und freigeben am: Sonntag, 12. Januar 2020, 13:03, cj\n\n--- AKTUELLE MA-LISTE ---\n\nP------------------------\n\n--- HINWEISE ---\n1. Bitte TAB-TASTE (Tabulator) zwischen den \"Spalten\" benutzen! KEINE LEERZEICHEN!\n2. Die Spalten \"AS\", \"LA#\" und \"T#\" sind in der Regel immer gleich. Die Werte können einfach kopiert und am Ende nach der Stundeneingabe eingefügt werden.\n3. In der ersten Zeile des Bearbeitungsabschnitts (507524 ...) bitte immer NUR Monat/Jahr anpassen!\n-----------------\n\n*\t*\t*\nP-Nr\tTag\tStd\tAS\tLA#\tT#\n\t\t\t1\t2200\t1\n\n------------------------------------\n--- Bearbeitungsabschnitt ---\n\n507524\t10004\t01/2020\n2\t4\t3,5\t1\t2200\t1\n2\t12\t8,75\t1\t2200\t1\n4\t10\t7,5\t1\t2200\t1\n4\t12\t6,5\t1\t2200\t1\n\n\n\n--- Bearbeitungsabschnitt Ende ---\n----------------------------------\n\nErläuterungen:\n\nAusfallschlüssel (AS)\t\r\n0\tfrei\r\n1\tgearbeitet\r\nK\tAU eingereicht\r\n\t\r\nLohnartnummer (LA#)\r\n2200\tAushilfe, Std\r\n2000\tGehalt",false,false,null,"/remote.php/dav/files/.../S1-E-Akten/.../Stunden_2020_01.txt"]},{"file":"/home/www/secure/apps/text/lib/Controller/SessionController.php","line":77,"function":"sync","class":"OCA\\Text\\Service\\ApiService","type":"->","args":[2070521,43,"ziRdLMwYkh9rL3+I9BbYXrAfyPv1t7CUj7+EOPB+NZmt69wHtjzhew1sTQyy/WNs",572,"Erfassung beendet und freigeben am: Sonntag, 12. Januar 2020, 13:03, cj\n\n--- AKTUELLE MA-LISTE ---\n\nP-...------------------------\n\n--- HINWEISE ---\n1. Bitte TAB-TASTE (Tabulator) zwischen den \"Spalten\" benutzen! KEINE LEERZEICHEN!\n2. Die Spalten \"AS\", \"LA#\" und \"T#\" sind in der Regel immer gleich. Die Werte können einfach kopiert und am Ende nach der Stundeneingabe eingefügt werden.\n3. In der ersten Zeile des Bearbeitungsabschnitts (507524 ...) bitte immer NUR Monat/Jahr anpassen!\n-----------------\n\n*\t*\t*\nP-Nr\tTag\tStd\tAS\tLA#\tT#\n\t\t\t1\t2200\t1\n\n------------------------------------\n--- Bearbeitungsabschnitt ---\n\n507524\t10004\t01/2020\n2\t4\t3,5\t1\t2200\t1\n2\t12\t8,75\t1\t2200\t1\n4\t10\t7,5\t1\t2200\t1\n4\t12\t6,5\t1\t2200\t1\n\n\n\n--- Bearbeitungsabschnitt Ende ---\n----------------------------------\n\nErläuterungen:\n\nAusfallschlüssel (AS)\t\r\n0\tfrei\r\n1\tgearbeitet\r\nK\tAU eingereicht\r\n\t\r\nLohnartnummer (LA#)\r\n2200\tAushilfe, Std\r\n2000\tGehalt",false,false]},{"file":"/home/www/secure/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"sync","class":"OCA\\Text\\Controller\\SessionController","type":"->","args":[2070521,43,"ziRdLMwYkh9rL3+I9BbYXrAfyPv1t7CUj7+EOPB+NZmt69wHtjzhew1sTQyy/WNs",572,"Erfassung beendet und freigeben am: Sonntag, 12. Januar 2020, 13:03, cj\n\n--- AKTUELLE MA-LISTE ---\n\nP-....------------------------\n\n--- HINWEISE ---\n1. Bitte TAB-TASTE (Tabulator) zwischen den \"Spalten\" benutzen! KEINE LEERZEICHEN!\n2. Die Spalten \"AS\", \"LA#\" und \"T#\" sind in der Regel immer gleich. Die Werte können einfach kopiert und am Ende nach der Stundeneingabe eingefügt werden.\n3. In der ersten Zeile des Bearbeitungsabschnitts (507524 ...) bitte immer NUR Monat/Jahr anpassen!\n-----------------\n\n*\t*\t*\nP-Nr\tTag\tStd\tAS\tLA#\tT#\n\t\t\t1\t2200\t1\n\n------------------------------------\n--- Bearbeitungsabschnitt ---\n\n507524\t10004\t01/2020\n2\t4\t3,5\t1\t2200\t1\n2\t12\t8,75\t1\t2200\t1\n4\t10\t7,5\t1\t2200\t1\n4\t12\t6,5\t1\t2200\t1\n\n\n\n--- Bearbeitungsabschnitt Ende ---\n----------------------------------\n\nErläuterungen:\n\nAusfallschlüssel (AS)\t\r\n0\tfrei\r\n1\tgearbeitet\r\nK\tAU eingereicht\r\n\t\r\nLohnartnummer (LA#)\r\n2200\tAushilfe, Std\r\n2000\tGehalt",false,false]},{"file":"/home/www/secure/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Text\\Controller\\SessionController"},"sync"]},{"file":"/home/www/secure/lib/private/AppFramework/App.php","line":126,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Text\\Controller\\SessionController"},"sync"]},{"file":"/home/www/secure/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Text\\Controller\\SessionController","sync",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"text.Session.sync"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"text.Session.sync"}]},{"file":"/home/www/secure/lib/private/Route/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"text.Session.sync"}]},{"file":"/home/www/secure/lib/base.php","line":997,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/text/session/sync"]},{"file":"/home/www/secure/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/home/www/secure/lib/private/Lock/DBLockingProvider.php","Line":264,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.4 Safari/605.1.15","version":"17.0.2.1","id":"5e2b2cf5ca852"}

**Comment by mejo-** [comment] 2022-11-01 10:31
<details>
<summary>Pretty-formated logtrace</summary>

```json
{
  "Exception": "OCP\\Lock\\LockedException",
  "Message": "files/b2d1648201a43079f91b07e4ce977d5b is locked",
  "Code": 0,
  "Trace": [
    {
      "file": "/home/www/secure/lib/private/Files/Storage/Common.php",
      "line": 807,
      "function": "changeLock",
      "class": "OC\\Lock\\DBLockingProvider",
      "type": "->",
      "args": [
        "files/b2d1648201a43079f91b07e4ce977d5b",
        2
      ]
    },
    {
      "file": "/home/www/secure/lib/private/Files/Storage/Wrapper/Wrapper.php",
      "line": 615,
      "function": "changeLock",
      "class": "OC\\Files\\Storage\\Common",
      "type": "->",
      "args": [
        "...LoBu/Stundenerfassung/Stunden_2020_01.txt",
        2,
        {
          "class": "OC\\Lock\\DBLockingProvider"
        }
      ]
    },
    {
      "file": "/home/www/secure/lib/private/Files/Storage/Wrapper/Wrapper.php",
      "line": 615,
      "function": "changeLock",
      "class": "OC\\Files\\Storage\\Wrapper\\Wrapper",
      "type": "->",
      "args": [
        "100338/Stundenerfassung/Stunden_2020_01.txt",
        2,
        {
          "class": "OC\\Lock\\DBLockingProvider"
        }
      ]
    },
    {
      "file": "/home/www/secure/lib/private/Files/Storage/Wrapper/Wrapper.php",
      "line": 615,
      "function": "changeLock",
      "class": "OC\\Files\\Storage\\Wrapper\\Wrapper",
      "type": "->",
      "args": [
        "100338/Stundenerfassung/Stunden_2020_01.txt",
        2,
        {
          "class": "OC\\Lock\\DBLockingProvider"
        }
      ]
    },
    {
      "file": "/home/www/secure/lib/private/Files/Storage/Wrapper/Wrapper.php",
      "line": 615,
      "function": "changeLock",
      "class": "OC\\Files\\Storage\\Wrapper\\Wrapper",
      "type": "->",
      "args": [
        "100338/Stundenerfassung/Stunden_2020_01.txt",
        2,
        {
          "class": "OC\\Lock\\DBLockingProvider"
        }
      ]
    },
    {
      "file": "/home/www/secure/lib/private/Files/Storage/Wrapper/Wrapper.php",
      "line": 615,
      "function": "changeLock",
      "class": "OC\\Files\\Storage\\Wrapper\\Wrapper",
      "type": "->",
      "args": [
        "100338/Stundenerfassung/Stunden_2020_01.txt",
        2,
        {
          "class": "OC\\Lock\\DBLockingProvider"
        }
      ]
    },
    {
      "file": "/home/www/secure/lib/private/Files/View.php",
      "line": 1981,
      "function": "changeLock",
      "class": "OC\\Files\\Storage\\Wrapper\\Wrapper",
      "type": "->",
      "args": [
        "100338/Stundenerfassung/Stunden_2020_01.txt",
        2,
        {
          "class": "OC\\Lock\\DBLockingProvider"
        }
      ]
    },
    {
      "file": "/home/www/secure/lib/private/Files/View.php",
      "line": 1149,
      "function": "changeLock",
      "class": "OC\\Files\\View",
      "type": "->",
      "args": [
        "/.../files/S1-E-Akten/100338/Stundenerfassung/Stunden_2020_01.txt",
        2
      ]
    },
    {
      "file": "/home/www/secure/lib/private/Files/View.php",
      "line": 694,
      "function": "basicOperation",
      "class": "OC\\Files\\View",
      "type": "->",
      "args": [
        "file_put_contents",
        "/.../files/S1-E-Akten/100338-.../LoBu/Stundenerfassung/Stunden_2020_01.txt",
        [
          "update",
          "write"
        ],
        "Erfassung beendet und freigeben am: Sonntag, 12. Januar 2020, 13:03, cj\n\n--- AKTUELLE MA-LISTE ---\n\nP-...------------------------\n\n--- HINWEISE ---\n1. Bitte TAB-TASTE (Tabulator) zwischen den \"Spalten\" benutzen! KEINE LEERZEICHEN!\n2. Die Spalten \"AS\", \"LA#\" und \"T#\" sind in der Regel immer gleich. Die Werte können einfach kopiert und am Ende nach der Stundeneingabe eingefügt werden.\n3. In der ersten Zeile des Bearbeitungsabschnitts (507524 ...) bitte immer NUR Monat/Jahr anpassen!\n-----------------\n\n*\t*\t*\nP-Nr\tTag\tStd\tAS\tLA#\tT#\n\t\t\t1\t2200\t1\n\n------------------------------------\n--- Bearbeitungsabschnitt ---\n\n507524\t10004\t01/2020\n2\t4\t3,5\t1\t2200\t1\n2\t12\t8,75\t1\t2200\t1\n4\t10\t7,5\t1\t2200\t1\n4\t12\t6,5\t1\t2200\t1\n\n\n\n--- Bearbeitungsabschnitt Ende ---\n----------------------------------\n\nErläuterungen:\n\nAusfallschlüssel (AS)\t\\r\n0\tfrei\\r\n1\tgearbeitet\\r\nK\tAU eingereicht\\r\n\t\\r\nLohnartnummer (LA#)\\r\n2200\tAushilfe, Std\\r\n2000\tGehalt"
      ]
    },
    {
      "file": "/home/www/secure/lib/private/Files/Node/File.php",
      "line": 66,
      "function": "file_put_contents",
      "class": "OC\\Files\\View",
      "type": "->",
      "args": [
        "/.../files/S1-E-Akten/.../Stundenerfassung/Stunden_2020_01.txt",
        "Erfassung beendet und freigeben am: Sonntag, 12. Januar 2020, 13:03, cj\n\n--- AKTUELLE MA-LISTE ---\n\nP-...n------------------------\n\n--- HINWEISE ---\n1. Bitte TAB-TASTE (Tabulator) zwischen den \"Spalten\" benutzen! KEINE LEERZEICHEN!\n2. Die Spalten \"AS\", \"LA#\" und \"T#\" sind in der Regel immer gleich. Die Werte können einfach kopiert und am Ende nach der Stundeneingabe eingefügt werden.\n3. In der ersten Zeile des Bearbeitungsabschnitts (507524 ...) bitte immer NUR Monat/Jahr anpassen!\n-----------------\n\n*\t*\t*\nP-Nr\tTag\tStd\tAS\tLA#\tT#\n\t\t\t1\t2200\t1\n\n------------------------------------\n--- Bearbeitungsabschnitt ---\n\n507524\t10004\t01/2020\n2\t4\t3,5\t1\t2200\t1\n2\t12\t8,75\t1\t2200\t1\n4\t10\t7,5\t1\t2200\t1\n4\t12\t6,5\t1\t2200\t1\n\n\n\n--- Bearbeitungsabschnitt Ende ---\n----------------------------------\n\nErläuterungen:\n\nAusfallschlüssel (AS)\t\\r\n0\tfrei\\r\n1\tgearbeitet\\r\nK\tAU eingereicht\\r\n\t\\r\nLohnartnummer (LA#)\\r\n2200\tAushilfe, Std\\r\n2000\tGehalt"
      ]
    },
    {
      "file": "/home/www/secure/apps/text/lib/Service/DocumentService.php",
      "line": 272,
      "function": "putContent",
      "class": "OC\\Files\node\\File",
      "type": "->",
      "args": [
        "Erfassung beendet und freigeben am: Sonntag, 12. Januar 2020, 13:03, cj\n\n--- AKTUELLE MA-LISTE ---\n\nP-...------------------------\n\n--- HINWEISE ---\n1. Bitte TAB-TASTE (Tabulator) zwischen den \"Spalten\" benutzen! KEINE LEERZEICHEN!\n2. Die Spalten \"AS\", \"LA#\" und \"T#\" sind in der Regel immer gleich. Die Werte können einfach kopiert und am Ende nach der Stundeneingabe eingefügt werden.\n3. In der ersten Zeile des Bearbeitungsabschnitts (507524 ...) bitte immer NUR Monat/Jahr anpassen!\n-----------------\n\n*\t*\t*\nP-Nr\tTag\tStd\tAS\tLA#\tT#\n\t\t\t1\t2200\t1\n\n------------------------------------\n--- Bearbeitungsabschnitt ---...-- Bearbeitungsabschnitt Ende ---\n----------------------------------\n\nErläuterungen:\n\nAusfallschlüssel (AS)\t\\r\n0\tfrei\\r\n1\tgearbeitet\\r\nK\tAU eingereicht\\r\n\t\\r\nLohnartnummer (LA#)\\r\n2200\tAushilfe, Std\\r\n2000\tGehalt"
      ]
    },
    {
      "file": "/home/www/secure/apps/text/lib/Service/ApiService.php",
      "line": 166,
      "function": "autosave",
      "class": "OCA\text\\Service\\DocumentService",
      "type": "->",
      "args": [
        2070521,
        572,
        "Erfassung beendet und freigeben am: Sonntag, 12. Januar 2020, 13:03, cj\n\n--- AKTUELLE MA-LISTE ---\n\nP------------------------\n\n--- HINWEISE ---\n1. Bitte TAB-TASTE (Tabulator) zwischen den \"Spalten\" benutzen! KEINE LEERZEICHEN!\n2. Die Spalten \"AS\", \"LA#\" und \"T#\" sind in der Regel immer gleich. Die Werte können einfach kopiert und am Ende nach der Stundeneingabe eingefügt werden.\n3. In der ersten Zeile des Bearbeitungsabschnitts (507524 ...) bitte immer NUR Monat/Jahr anpassen!\n-----------------\n\n*\t*\t*\nP-Nr\tTag\tStd\tAS\tLA#\tT#\n\t\t\t1\t2200\t1\n\n------------------------------------\n--- Bearbeitungsabschnitt ---\n\n507524\t10004\t01/2020\n2\t4\t3,5\t1\t2200\t1\n2\t12\t8,75\t1\t2200\t1\n4\t10\t7,5\t1\t2200\t1\n4\t12\t6,5\t1\t2200\t1\n\n\n\n--- Bearbeitungsabschnitt Ende ---\n----------------------------------\n\nErläuterungen:\n\nAusfallschlüssel (AS)\t\\r\n0\tfrei\\r\n1\tgearbeitet\\r\nK\tAU eingereicht\\r\n\t\\r\nLohnartnummer (LA#)\\r\n2200\tAushilfe, Std\\r\n2000\tGehalt",
        false,
        false,
        null,
        "/remote.php/dav/files/.../S1-E-Akten/.../Stunden_2020_01.txt"
      ]
    },
    {
      "file": "/home/www/secure/apps/text/lib/Controller/SessionController.php",
      "line": 77,
      "function": "sync",
      "class": "OCA\text\\Service\\ApiService",
      "type": "->",
      "args": [
        2070521,
        43,
        "ziRdLMwYkh9rL3+I9BbYXrAfyPv1t7CUj7+EOPB+NZmt69wHtjzhew1sTQyy/WNs",
        572,
        "Erfassung beendet und freigeben am: Sonntag, 12. Januar 2020, 13:03, cj\n\n--- AKTUELLE MA-LISTE ---\n\nP-...------------------------\n\n--- HINWEISE ---\n1. Bitte TAB-TASTE (Tabulator) zwischen den \"Spalten\" benutzen! KEINE LEERZEICHEN!\n2. Die Spalten \"AS\", \"LA#\" und \"T#\" sind in der Regel immer gleich. Die Werte können einfach kopiert und am Ende nach der Stundeneingabe eingefügt werden.\n3. In der ersten Zeile des Bearbeitungsabschnitts (507524 ...) bitte immer NUR Monat/Jahr anpassen!\n-----------------\n\n*\t*\t*\nP-Nr\tTag\tStd\tAS\tLA#\tT#\n\t\t\t1\t2200\t1\n\n------------------------------------\n--- Bearbeitungsabschnitt ---\n\n507524\t10004\t01/2020\n2\t4\t3,5\t1\t2200\t1\n2\t12\t8,75\t1\t2200\t1\n4\t10\t7,5\t1\t2200\t1\n4\t12\t6,5\t1\t2200\t1\n\n\n\n--- Bearbeitungsabschnitt Ende ---\n----------------------------------\n\nErläuterungen:\n\nAusfallschlüssel (AS)\t\\r\n0\tfrei\\r\n1\tgearbeitet\\r\nK\tAU eingereicht\\r\n\t\\r\nLohnartnummer (LA#)\\r\n2200\tAushilfe, Std\\r\n2000\tGehalt",
        false,
        false
      ]
    },
    {
      "file": "/home/www/secure/lib/private/AppFramework/Http/Dispatcher.php",
      "line": 170,
      "function": "sync",
      "class": "OCA\text\\Controller\\SessionController",
      "type": "->",
      "args": [
        2070521,
        43,
        "ziRdLMwYkh9rL3+I9BbYXrAfyPv1t7CUj7+EOPB+NZmt69wHtjzhew1sTQyy/WNs",
        572,
        "Erfassung beendet und freigeben am: Sonntag, 12. Januar 2020, 13:03, cj\n\n--- AKTUELLE MA-LISTE ---\n\nP-....------------------------\n\n--- HINWEISE ---\n1. Bitte TAB-TASTE (Tabulator) zwischen den \"Spalten\" benutzen! KEINE LEERZEICHEN!\n2. Die Spalten \"AS\", \"LA#\" und \"T#\" sind in der Regel immer gleich. Die Werte können einfach kopiert und am Ende nach der Stundeneingabe eingefügt werden.\n3. In der ersten Zeile des Bearbeitungsabschnitts (507524 ...) bitte immer NUR Monat/Jahr anpassen!\n-----------------\n\n*\t*\t*\nP-Nr\tTag\tStd\tAS\tLA#\tT#\n\t\t\t1\t2200\t1\n\n------------------------------------\n--- Bearbeitungsabschnitt ---\n\n507524\t10004\t01/2020\n2\t4\t3,5\t1\t2200\t1\n2\t12\t8,75\t1\t2200\t1\n4\t10\t7,5\t1\t2200\t1\n4\t12\t6,5\t1\t2200\t1\n\n\n\n--- Bearbeitungsabschnitt Ende ---\n----------------------------------\n\nErläuterungen:\n\nAusfallschlüssel (AS)\t\\r\n0\tfrei\\r\n1\tgearbeitet\\r\nK\tAU eingereicht\\r\n\t\\r\nLohnartnummer (LA#)\\r\n2200\tAushilfe, Std\\r\n2000\tGehalt",
        false,
        false
      ]
    },
    {
      "file": "/home/www/secure/lib/private/AppFramework/Http/Dispatcher.php",
      "line": 99,
      "function": "executeController",
      "class": "OC\\AppFramework\\Http\\Dispatcher",
      "type": "->",
      "args": [
        {
          "class": "OCA\text\\Controller\\SessionController"
        },
        "sync"
      ]
    },
    {
      "file": "/home/www/secure/lib/private/AppFramework/App.php",
      "line": 126,
      "function": "dispatch",
      "class": "OC\\AppFramework\\Http\\Dispatcher",
      "type": "->",
      "args": [
        {
          "class": "OCA\text\\Controller\\SessionController"
        },
        "sync"
      ]
    },
    {
      "file": "/home/www/secure/lib/private/AppFramework/Routing/RouteActionHandler.php",
      "line": 47,
      "function": "main",
      "class": "OC\\AppFramework\\App",
      "type": "::",
      "args": [
        "OCA\text\\Controller\\SessionController",
        "sync",
        {
          "class": "OC\\AppFramework\\DependencyInjection\\DIContainer"
        },
        {
          "_route": "text.Session.sync"
        }
      ]
    },
    {
      "function": "__invoke",
      "class": "OC\\AppFramework\\Routing\\RouteActionHandler",
      "type": "->",
      "args": [
        {
          "_route": "text.Session.sync"
        }
      ]
    },
    {
      "file": "/home/www/secure/lib/private/Route/Router.php",
      "line": 297,
      "function": "call_user_func",
      "args": [
        {
          "class": "OC\\AppFramework\\Routing\\RouteActionHandler"
        },
        {
          "_route": "text.Session.sync"
        }
      ]
    },
    {
      "file": "/home/www/secure/lib/base.php",
      "line": 997,
      "function": "match",
      "class": "OC\\Route\\Router",
      "type": "->",
      "args": [
        "/apps/text/session/sync"
      ]
    },
    {
      "file": "/home/www/secure/index.php",
      "line": 42,
      "function": "handleRequest",
      "class": "OC",
      "type": "::",
      "args": []
    }
  ],
  "File": "/home/www/secure/lib/private/Lock/DBLockingProvider.php",
  "Line": 264,
  "CustomMessage": "--"
}
```
</details>

**Comment by mejo-** [comment] 2022-11-01 10:48
I'm not able to reproduce this bug on latest Nextcloud 25. File lock handling has changed a bit since this bug got reported so it's quite possible that it got fixed in the meantime. Closing the issue for now, but don't hesitate to reopen it if you still encounter the issue @cju77.

**Closed by mejo-** 2022-11-01 10:48 UTC
Labels: bug, 1. to develop, needs triage: jonas
