### ISSUE TITLE
.md and .txt files in a folder shared read-only by share link can't be viewed

### ISSUE THREAD

**Issue by alarmix** [nextcloud/text#3344] opened 2022-10-30 18:47 UTC
**Describe the bug**
.txt and .md files in a read-only folder shared by share link can't be viewed.

**To Reproduce**
1. Go to any folder containing .md and/or .txt files
2. Share the folder read-only with a share link
3. Open the share link in another browser or an incognito window
4. Opening the .txt/.md file, the file contents are not visible, only the file name at the top.

**Expected behavior**
.md/.txt files should be able to be viewed, without the possibility to edit/modify them

**Screenshots**
![image](https://user-images.githubusercontent.com/47664465/198896021-400e2d08-6967-4193-8ddd-ce52f4ea2d5f.png)

**Client details:**
 - OS: linux
 - Browser: chromium
 - Version: Version 106.0.5249.119 (Official Build) built on Debian 11.5, running on Debian 11.5 (64-bit)
 - Device: desktop

<details>
<summary>Server details</summary>

**Text app version:** 	3.5.1

**Operating system:** Debian 11.5 (64-bit)

**Web server:** apache2 2.4.54-1~deb11u1 amd64

**Database:** mariadb-server-10.5 1:10.5.15-0+deb11u1 amd64

**PHP version:** 8.0.24

**Nextcloud version:** 24.0.6

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
nothing relevant
```

#### Browser log
```
xhr.js:220          PUT https://xxxxxxxxxxx/index.php/apps/text/session/create 401 (Unauthorized)
```

</details>

**Comment by juliushaertl** [comment] 2022-11-02 12:00
I cannot reproduce this issue on 24.0.6, but the URL that is being requested from the browser seems to be the wrong one `/index.php/apps/text/public/session/create` should be used for public share links.

Could you maybe share a screenshot of the exact share permissions set for the link? Any change you can provide a link to an example file on the instance where that is an issue?

**Comment by alarmix** [comment] 2022-11-02 13:52
yes, it is a public share link
![image](https://user-images.githubusercontent.com/47664465/199506917-e2311d62-ff07-4cdd-86e9-7e5363df30fa.png)

**Comment by alarmix** [comment] 2022-11-02 13:55
I'll create a similar scenario without sensitive info in the folder, and share the link with you later tonight.

**Comment by alarmix** [comment] 2022-11-05 14:29
sorry for the dely, now the test share is ready
can I send you the url in email to your github address?

**Comment by juliushaertl** [comment] 2022-11-07 07:18
Great, yes, feel free to send it to the mail address in my profile :)

**Comment by juliushaertl** [comment] 2023-06-06 18:17
@alarmix Sorry this has totally slipped through. Do you still see this issue happening? If that is the case maybe you could be so kind to send another fresh share link by mail?

**Comment by mejo-** [comment] 2023-07-25 06:18
I'll close this due to lack of information. Feel free to reopen with further information if you still encounter this bug.

**Closed by mejo-** 2023-07-25 06:18 UTC
Labels: bug, needs info, needs triage: julius
