### ISSUE TITLE
[Bug]: Markdown syntax is not parsed while pasting from clipboard (WEB)

### ISSUE THREAD

**Issue by bvn13** [nextcloud/text#2683] opened 2022-07-06 09:25 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

1. Take my markdown snippet, copy it in cliipboard
2. Go nextcloud web, create new file
3. Paste my snippet from clipboard
4. Check out the syntax is parsed partially

Snippet:
```
# Test heading 1

text 1

## test heading 2

### test heading 3

test text. `test test`
```

Take a look at my screenshot for details, please.

### Steps to reproduce

see above

### Expected behavior

see above

### Installation method

Official Docker image

### Operating system

Debian/Ubuntu

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
--
```

**Comment by susnux** [comment] 2022-07-06 17:31
Duplicate of https://github.com/nextcloud/text/issues/16

**Closed** 2022-07-06 18:05 UTC
Labels: bug, 0. Needs triage
