### ISSUE TITLE
Rename a file when it's open in Text

### ISSUE THREAD

**Issue by nimishavijay** [nextcloud/text#5382] opened 2024-02-15 10:36 UTC
**Is your feature request related to a problem? Please describe.**
Sometimes I want to quickly create a text file to take some notes, and when I want to change its name later, I have to: 
1. close the file, 
2. find the file in the files list
3. go to the 3 dot menu of the file
4. select rename
5. type the new name 
6. press enter/click elsewhere. 

This is a long and possibly not so intuitive process.

**Describe the solution you'd like**
Be able to rename files from within Text itself.

Many products have this feature. ex. Google Docs

https://github.com/nextcloud/text/assets/52440189/ea045e29-6b26-42fa-8289-b62dd10e456f

Notion

https://github.com/nextcloud/text/assets/52440189/29693aea-5f3a-4b7f-9043-5dbb3f5bb04d

MS Office

https://github.com/nextcloud/text/assets/52440189/ec3a27a0-dd9a-4d29-90eb-0b476280393a

In a similar way, clicking on the name of the file in Text could allow renaming.

**Describe alternatives you've considered**
Add a rename item in the top right action menu

**Additional context**
n/a

**Comment by juliushaertl** [comment] 2024-02-15 11:34
This probably needs to be implemented in the viewer, could also be useful for other types like pdf.

**Comment by szaimen** [comment] 2024-02-15 14:14
> This probably needs to be implemented in the viewer, could also be useful for other types like pdf.

agreed

**Comment by jancborchardt** [comment] 2024-03-08 10:35
Closing this as duplicate of https://github.com/nextcloud/viewer/issues/2079 then. :)

**Closed by jancborchardt** 2024-03-08 10:35 UTC
Labels: enhancement, design, ux, feature: direct editor
