### ISSUE TITLE
consolidate header and paragraph buttons?

### ISSUE THREAD

**Issue by brainchild0** [nextcloud/text#353] opened 2019-10-09 17:29 UTC
I tried the "paragraph" button many times, attempting to discover its function.  It never seemed to have any effect.  I almost gave up before realizing that paragraph means not header.  

Maybe the paragraph and header buttons should be consolidated.  Regular body text might just be one of the drop down options, in addition to the header levels.  

I never saw this kind of interface before.  I think it is probably confusing since there are so many rich text editors that have a different solution.

**Comment by jancborchardt** [comment] 2019-10-16 20:11
> Maybe the paragraph and header buttons should be consolidated. Regular body text might just be one of the drop down options, in addition to the header levels.

Yeah, I’d say that’s a good point. But then we have to have an `.icon-caret` below the icon to indicate it’s a menu. @juliushaertl?

**Comment by brainchild0** [comment] 2019-10-16 21:04
Whatever you have in the header button seems   clear, at least on the question of a drop-down menu.  You can probably just move the paragraph icon into the header menu.   Even the existing icon for the header menu is probably fine. The paragraph icon is not intuitive shown in isolation, but the  juxtaposition  to the header options  probably expresses the concept with adequate clarity.

**Comment by jancborchardt** [comment] 2019-10-16 21:14
The issue is that the default action icon of the menu also functions as the icon of what is currently active.

And since everything is basically normal paragraph by default, it will show the paragraph icon and you might never click it. This is why it needs a caret.

**Comment by brainchild0** [comment] 2019-10-16 21:22
I see.  I definitely support an indication of the drop-down menu whenever there is one.

Regarding the issue of icon, perhaps the user would be best guided by continued use of the header icon.  The menu has three functions: to make a regular paragraph into a header, to make a header into a paragraph, and to change a header level. All three cases involve a header, so the header icon carries the needed information.

**Comment by brainchild0** [comment] 2019-10-19 22:55
Another option is to use buttons (and keyboard shortcuts) that promote or demote header level (with a body paragraph having the position of level-zero header), rather than setting the level to a chosen value.  Most invocations of commands related to header level will be to promote or demote a header level one position, or to set a paragraph to a header immediately after it is typed.

**Comment by azul** [comment] 2020-08-12 10:28
I landed here because i was searching the repo to learn if the para button had any function. I think the current icon is really confusing. For me it's a symbol of a line break / para break. Not the unformatted text itself.

I'd just drop the Paragraph button completely. You can turn a heading into a para by clicking the name of the heading again. Just like you can turn bold into normal text by clicking bold again.

If you just turned something into a heading accidentally undo will also work.

**Comment by juliushaertl** [comment] 2020-08-12 10:42
Sounds good to me :+1:

**Closed** 2020-08-13 06:04 UTC
Labels: design, enhancement
