### ISSUE TITLE
Add the ability to see the color of the differents authors

### ISSUE THREAD

**Issue by yodatak** [nextcloud/text#260] opened 2019-08-22 20:47 UTC
**Is your feature request related to a problem? Please describe.**
I want to know with author is writing and what does is does like if it add a word i want to see the modification

**Describe the solution you'd like**
An idea of the solution will be to do something like etherpad and add color for etch user or a fancy annimation

by exemple : 
https://mensuel.framapad.org/p/Va4yx60jcGawKowNCX37

**Comment by juliushaertl** [comment] 2019-08-23 08:33
Duplicate of https://github.com/nextcloud/text/issues/91

Let me rename that so it is a bit easier to find.

**Closed by juliushaertl** 2019-08-23 08:33 UTC
Labels: enhancement
