### ISSUE TITLE
 Weird text editing behavior

### ISSUE THREAD

**Issue by fsoc** [nextcloud/text#1927] opened 2021-11-02 09:19 UTC
**Describe the bug**
Text is deleted when editing. All details including videos are reported in:
https://github.com/nextcloud/ios/issues/1631

https://user-images.githubusercontent.com/606665/128668738-c2ea981b-f6b2-4322-a274-737a43cfb224.mp4

**Comment by juliushaertl** [comment] 2021-11-03 21:28
Seems to be an issue on the web with safari as well. So far the reports only seem to mention 22.2.0

**Comment by Norjek** [comment] 2021-11-19 13:56
I can confirm, problem appears in Safari and/or iOS Nextcloud App (4.0.6), and since we upgraded to 22.2.0

A return/new line, at the end of a textline, moves the cursor to the top of the file and inserts the new line there - always.
Adding other letters to the end of the line (e.g. H) works though.
Pasting content or adding a new line at an empty line, sometimes even clears the entire file adding a single empty line at the start of the file.
With that "new" Autosave-function, this deletes everything and saves instantly, which is pretty annoying.

**Comment by Norjek** [comment] 2021-12-22 07:40
There have been updates and bugfixes, of course I installed the updates:
Nextcloud iOS App 4.2.0.5
Nextcloud Server 22.2.3

Sadly the problem is still existing. Basically working with Textfiles is impossible as  User because the problem appears on Safari as well. I‘d be happy if that could be fixed, data loss is extremely annoying.

**Comment by fsoc** [comment] 2022-04-22 12:20
Yet another document dissapeared thanks to this bug. Can you report on the timeline of solving this? Happened on IOS app 4.3.1.0 NC 23.0.3. Can you please prioritize this? 

The bug is intermittent, so the use case does sometimes work.

**Comment by ftoomch82** [comment] 2022-05-27 14:50
This is still happening with yesterday's updated iOS client.

Server version: a very nearly default ```24.0.1```
My user agent ```Mozilla/5.0 (iOS) Nextcloud-iOS/4.4.0 AppleWebKit/605.1.15 Mobile/15E148```
iOS ```15.4.1```

**Comment by juliushaertl** [comment] 2022-10-17 17:59
Might also be related to https://github.com/nextcloud/text/issues/2131

**Comment by fsoc** [comment] 2022-10-17 19:51
please help us with this issue. It has persisted through several Nextcloud versions for a year and it still happens now and then that the whole file gets deleted.

 I started to locally save a copy before editing every time as a workaround a fix for this would make many peoples life’s easier!

**Comment by juliushaertl** [comment] 2022-11-18 07:39
Seems ot only be an issue with plain txt file now (no longer with markdown files)

**Comment by f1d094** [comment] 2022-12-08 01:48
This issue is still ongoing as of Nextcloud for iOS version 4.5.7

Editing plain text files results in deleted content.

**Comment by f1d094** [comment] 2022-12-08 16:09
I failed to make a few important notes:
1) Server was running 23.0.11 and client 4.5.7
2) After upgrading server to 24.0.7 the issue is largely resolved. Attempting to enter a newline between existing text no longer deletes random blocks of text.

Related: Hitting return on a blank line creates a newline and then deletes it...but if you are quick and hit enter a few times it creates 'n' newlines and only deletes the last one.

**Comment by mejo-** [comment] 2024-09-11 10:45
Let's close this for now. Anybody who still exeriences this, please comment and we'll reopen the issue.

**Closed by mejo-** 2024-09-11 10:45 UTC
Labels: bug, 1. to develop, needs info, format: plaintext, Android, mobile, high, iOS
