### ISSUE TITLE
support YAML headers

### ISSUE THREAD

**Issue by brainchild0** [nextcloud/text#352] opened 2019-10-09 11:53 UTC
An emerging convention involves placing a YAML block at the head of a MarkDown document, to supply metadata that is part of the document but not correctly expressed in MarkDown.  Some included fields affect how a document might be optimally displayed, such as title, subtitle, author,  and date.

These blocks normally precede any other document content, and are delimited by lines consisting each of three or more dashes.  MarkDown engines that do not handle this convention specifically, normally interpret the trailing sequence of dashes to make the preceding line into a level-2 header.  The effect is unwanted display artifacts.

A growing number of MarkDown editors recognize this convention, either by merely suppressing regular MarkDown processing for the header, of by generating a display appropriate from the values in the header, such as the title.

I would suggest that Text might function better in a wider range of use cases if support of some such kind were available.

Jekyll and Pandoc are prominent examples of packages that utilize this convention, and their documentation explains the parsing rules.

**Comment by juliushaertl** [comment] 2019-10-09 13:59
@brainchild0 Thanks for your feature request. This is a duplicate of #145

**Closed by juliushaertl** 2019-10-09 13:59 UTC
Labels: enhancement
