### ISSUE TITLE
Emoji picker and "Insert image" should go into the overflow menu

### ISSUE THREAD

**Issue by luka-nextcloud** [nextcloud/text#2606] opened 2022-06-21 07:56 UTC
Emoji picker and "Insert image" should go into the overflow menu
- In the long run, we could group the items into few menus: Formatting, headings, etc – however we might not have enough space
- Possibly think about moving the formatting bar to the bottom on mobile

**Comment by juliushaertl** [comment] 2022-11-02 12:02
Closing as a duplicate of https://github.com/nextcloud/text/issues/2836 which contains more details about the mobile menu bar redesign

**Closed by juliushaertl** 2022-11-02 12:02 UTC
Labels: enhancement, 3. to review, needs triage: raul
