### ISSUE TITLE
Convert MD URL to "pretty view" 

### ISSUE THREAD

**Issue by stratacast** [nextcloud/text#393] opened 2019-10-31 02:06 UTC
**Describe the bug**
Currently if you type `###` in the editor, it'll switch the editor to H3 mode. It would be neat to see something similar with URLs.

**To Reproduce**
1. Open the editor
2. Use markdown formatting to create a URL with provided text

**Expected behavior**
Type something like:
`[Nextcloud](https://nextcloud.com)`

And the output becomes:
`Nextcloud` with a clickable hyperlink

**Screenshots**
![image](https://user-images.githubusercontent.com/14900584/67912416-1bd98200-fb47-11e9-9a01-b7301e940eea.png)

**Client details:**
 - OS: FreeBSD/Linux
 - Browser: Firefox
 - Version: 70
 - Device: Desktop

<details>
<summary>Server details</summary>

**Text app version:** 1.1.0
**Operating system:** FreeBSD 12.0

**Web server:** nginx/1.16

**Database:** mariadb 10.2

**PHP version:** 7.3

**Nextcloud version:** 17.0
</details>

<details>
<summary>Logs</summary>

#### Browser log
```
{
  "markdown": "## Yo\n\nHey there dood\n\n[Nextcloud](https://nextcloud.com)\n\n\\[Nextcloud\\](https://nextcloud.com)\n\n```\ndef main():\n    print(\"Hello world!\")\n```\n\nttt\n\nCan you see this? If so, type something\n\nHow about now?\n\nType something below this:\n\nok. does this thing work?\n\n### hjhhkuhuh\n\nujgjgjyg\n\n### HKUhiuhiuhihu\n\n\\[DuckDuckGo\\](\"https://duckduckgo.com)"
}
```

</details>

**Comment by juliushaertl** [comment] 2019-11-04 11:53
Duplicate of https://github.com/nextcloud/text/issues/55

**Closed by juliushaertl** 2019-11-04 11:53 UTC
Labels: bug
