### ISSUE TITLE
"File could not be loaded. Check your internet connection"

### ISSUE THREAD

**Issue by ciropom** [nextcloud/text#5939] opened 2024-06-23 14:09 UTC
**Describe the bug**
After a variable (small in the nextcloud app for android, large in browser) time without interaction,
the text app displays the message:

"File could not be loaded. Check your internet connection"

with a "Reconnect" button that doesn't work either.

**To Reproduce**
1. Open any md file
2. add/modify some text
3. change browser tab or android app for a while

**Expected behavior**
The text should remain editable even if I opened the file some time ago.

**Screenshots**
![Screenshot from 2024-06-23 15-58-57](https://github.com/nextcloud/text/assets/3096752/b0c4cc0d-9887-4f94-9ed0-e29fd4f6c2d4)
![Screenshot from 2024-06-23 16-11-02](https://github.com/nextcloud/text/assets/3096752/4ae8f7fc-31b8-4c55-80d7-b28cde0c2301)

**Server details:**
- Nextcloud version: 28.0.1
- PHP Version:  8.1
- Database: postgresql

**Client details:**
 - OS: Ubuntu
 - Browser: Chromimum 
 - Browser version: 125
 - Device: Android, desktop from web interface

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:



</details>

**Comment by juliushaertl** [comment] 2024-06-24 10:33
Thanks for reporting. This seems like a duplicate of https://github.com/nextcloud/android/issues/12138 with a possible fix in https://github.com/nextcloud/text/pull/5662

**Closed by juliushaertl** 2024-06-24 10:33 UTC
Labels: bug
