### ISSUE TITLE
Change default timeout

### ISSUE THREAD

**Issue by fwSmit** [nextcloud/text#1819] opened 2021-08-09 13:08 UTC
Sometimes I leave open the editor for a while and when I come back the document has timed out. The default timeout is 30 minutes, but I would like to change that, since I'm often running into that timeout. Is there already a configuration option for that or could that be added?

**Comment by juliushaertl** [comment] 2021-08-11 07:11
Closing as a duplicate of #1715

**Closed by juliushaertl** 2021-08-11 07:11 UTC
Labels: enhancement
